#!/usr/bin/env python3
"""
Build assets/shusage.js -- what each command does when you hand it a bad option.

    python3 tools/build_usage.py

There is no convention to guess at here, which is exactly why this is
generated. From a real RHEL 9 machine, on an unrecognised long option:

    76 commands exit 1        the GNU coreutils habit
    16 exit 2                 ls, grep, sort, diff, useradd, chage ...
     2 exit 64                getent, tar
     2 exit 125               env, nice
     4 exit 255               hostname, ip, ss, which
     1 exits 253              passwd
     1 exits 0                less

and 65 of them print `Try 'cmd --help' for more information.` on a second
line while the rest print nothing more, or a full usage summary first.

Nobody holds that in their head. The emulator used to answer `2` for
everything, so a learner writing `if [ $? -eq 1 ]` around `cp` would have been
taught the wrong number by a machine that looked authoritative.

The first line -- `cmd: unrecognized option '--x'` -- is still produced in
code, because it contains the option the learner actually typed. Everything
after it is replayed from here.
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
PROBES = os.path.join(HERE, "harvest", "out", "errors.json")
HELP = os.path.join(HERE, "harvest", "out", "help.json")
OUT = os.path.join(ROOT, "assets", "shusage.js")

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, ValueError):
    pass

# The generated first line, which we reproduce in code rather than replay.
FIRST_LINE = re.compile(r"^\S+: (unrecognized option|invalid option|"
                        r"unknown option|illegal option)\b")


def main():
    if not os.path.exists(PROBES):
        print("No harvested probes. Run: python3 tools/harvest.py")
        return 1

    with open(PROBES, encoding="utf-8") as fh:
        probes = json.load(fh)

    helps = {}
    if os.path.exists(HELP):
        with open(HELP, encoding="utf-8") as fh:
            helps = json.load(fh)

    table = {}
    for name, kinds in sorted(probes.items()):
        bad = kinds.get("bad-option")
        if not bad:
            continue
        lines = [l for l in (bad.get("stderr") or "").split("\n") if l.strip()]
        # Drop the line we generate ourselves; keep whatever followed it.
        tail = lines[1:] if lines and FIRST_LINE.match(lines[0]) else lines
        entry = {"status": bad.get("status", 1)}
        if tail:
            entry["tail"] = tail

        # A usage error (no operands at all) does not always exit the same way
        # as an unrecognised option, so it is recorded separately where the
        # probe caught one.
        none = kinds.get("no-args")
        if none and none.get("status"):
            entry["usageStatus"] = none["status"]

        table[name] = entry

    # `--help` text, which the emulator did not answer at all: `ls --help`
    # replied "unrecognized option '--help'" while the error above it advised
    # "Try 'ls --help' for more information". The study guide calls --help the
    # first thing to try, so it needs to be instant rather than fetched.
    for name, entry in sorted(helps.items()):
        text = entry.get("text") or ""
        if not text.strip():
            continue
        row = table.setdefault(name, {"status": 1})
        row["help"] = text.rstrip()
        if entry.get("status"):
            row["helpStatus"] = entry["status"]

    body = json.dumps(table, indent=1, ensure_ascii=False, sort_keys=True)

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("""/* ===========================================================================
 * GENERATED by tools/build_usage.py -- do not edit by hand.
 *
 * What a real RHEL 9 machine does when a command is given an option it does
 * not recognise: the exit code, and any lines it prints after the first.
 *
 * There is no rule to infer. 76 commands exit 1, 16 exit 2, and a handful
 * reach for 64, 125, 253 or 255. Two thirds add `Try 'cmd --help' for more
 * information.`; the rest do not. Guessing produced a machine that answered
 * 2 for everything and quietly taught the wrong number.
 *
 * Regenerate after a harvest:  python3 tools/build_usage.py
 * Check the result against reality:  node tools/check_errors.js
 * =========================================================================== */
const HarborUsage = """)
        fh.write(body)
        fh.write(""";

if (typeof module !== 'undefined' && module.exports) module.exports = HarborUsage;
else if (typeof HarborShell !== 'undefined') HarborShell.usage = HarborUsage;
""")

    size = os.path.getsize(OUT)
    codes = {}
    for entry in table.values():
        codes[entry["status"]] = codes.get(entry["status"], 0) + 1
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    print("  %d commands, %.1f KB" % (len(table), size / 1024.0))
    print("  exit codes: %s" % ", ".join(
        "%s->%d" % (k, v) for k, v in sorted(codes.items())))
    print("  %d also print a second line"
          % sum(1 for e in table.values() if e.get("tail")))
    print("  %d carry real --help text"
          % sum(1 for e in table.values() if e.get("help")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
