"""Question pool for the ITD 145 final exam review. Built by build_itd145_final.py.

mc(category, question, correct, [wrong, wrong, wrong], explanation)
tf(category, statement, answer, explanation)
fb(category, question, [accepted answers], explanation)
mt(category, question, [(left, right), ...], explanation)
sa(category, question, model_answer, [rubric criteria], explanation)

Distractors are written to match the right answer's length and detail -- see
CLAUDE.md. qcheck.length_bias() fails the build if they drift.

Questions are shuffled inside each section, so none may refer to another.
Anything that needs data carries its own copy of it (EMP below).
"""

_n = [0]


def mc(cat, q, correct, wrongs, expl):
    assert len(wrongs) == 3, q
    pos = _n[0] % 4
    _n[0] += 1
    opts = list(wrongs)
    opts.insert(pos, correct)
    return {"type": "mc", "category": cat, "question": q,
            "options": opts, "correct": pos, "explanation": expl}


def tf(cat, q, ans, expl):
    return {"type": "tf", "category": cat, "question": q, "correct": ans, "explanation": expl}


def fb(cat, q, answers, expl):
    return {"type": "fill_blank", "category": cat, "question": q, "answers": answers, "explanation": expl}


def mt(cat, q, pairs, expl):
    return {"type": "matching", "category": cat, "question": q,
            "pairs": [{"left": a, "right": b} for a, b in pairs], "explanation": expl}


def sa(cat, q, model, rubric, expl):
    return {"type": "short_answer", "category": cat, "question": q, "answerLang": None,
            "modelAnswer": model, "rubric": rubric, "explanation": expl}


# A small DataFrame used by many questions. Each question restates it.
EMP = ("The DataFrame emp has the columns dept, name, salary and years, with the default index 0 to 5:\n"
       "0: Sales, Ana, 52000, 3\n1: Sales, Ben, 61000, 7\n2: IT, Cy, 75000, 5\n"
       "3: IT, Dee, 82000, 9\n4: HR, Eli, 48000, 2\n5: HR, Fay, 55000, 6\n")

SECTIONS = []

# ======================================================================= 1
c = "Descriptive Statistics"
SECTIONS.append(("1. Descriptive Statistics", [
    mc(c, "A hospital wants the average wait time across all 12,000 of its yearly emergency visits, so it times 300 randomly chosen visits. The 300 visits are the ___.",
       "sample", ["population", "parameter", "census"],
       "The group you actually measure is the sample; the 12,000 visits are the population."),
    mc(c, "In the same study, the true average wait time across all 12,000 visits is a ___.",
       "parameter", ["statistic", "quartile", "sampling error"],
       "A number describing a population is a parameter. A number computed from a sample is a statistic."),
    mc(c, "Which pair of symbols correctly labels the sample mean and the population mean?",
       "x̄ (x-bar) for the sample mean and μ (mu) for the population mean",
       ["μ for the sample mean and x̄ for the population mean, since mu comes first",
        "σ for the sample mean and μ for the population mean, which is the usual pairing",
        "x̄ for both, because the two means are calculated with the same formula"],
       "x̄ is the sample statistic and μ is the population parameter. σ is the population standard deviation."),
    tf(c, "A sample mean will always be exactly equal to the mean of the population it was drawn from.", False,
       "Different random samples give different means. That sample-to-sample difference is sampling error."),
    mc(c, "A researcher doubles the size of a random sample. What is the most likely effect on the sample mean as an estimate of the population mean?",
       "It is likely to land closer to the population mean, because sampling error shrinks",
       ["It is guaranteed to equal the population mean, because the sample is larger now",
        "It becomes biased, because a larger sample is harder to select at random",
        "It is unchanged, because sample size has no effect on how accurate it is"],
       "Larger random samples reduce sampling error, but they cannot guarantee an exact match."),
    mc(c, "The values in a data set are 3, 5, 7, 7 and 8. Which comparison of the mean and the median is correct?",
       "the median (7) is greater than the mean (6)",
       ["the mean (6) is greater than the median (7)", "the mean and the median are both equal to 7", "the mean and the median are both equal to 6"],
       "Mean = 30 / 5 = 6; median = 7. The small values pull the mean below the median."),
    mc(c, "What is the median of the data set 4, 9, 12, 20?",
       "10.5", ["12", "9", "11.25"],
       "With an even count, average the two middle values: (9 + 12) / 2 = 10.5. The mean is 11.25."),
    mc(c, "Which measure of central tendency is least affected by a few extreme values?",
       "median", ["mean", "range", "maximum"],
       "The median depends only on the middle of the sorted data, so a huge or tiny value barely moves it."),
    mc(c, "A data set has a minimum of 5, Q1 = 14, a median of 30, Q3 = 38 and a maximum of 90. What is the interquartile range?",
       "24", ["33", "16", "85"],
       "IQR = Q3 − Q1 = 38 − 14 = 24. The other numbers are range-style traps: 38 − 5 = 33, 30 − 14 = 16, 90 − 5 = 85."),
    mc(c, "The second quartile (Q2) of a data set is the same as the ___.",
       "median", ["mean", "mode", "IQR"],
       "Q1, Q2 and Q3 mark the 25th, 50th and 75th percentiles; Q2 is the 50th, the median."),
    mc(c, "A data set has a variance of 49. What is its standard deviation?",
       "7", ["24.5", "49", "2401"],
       "The standard deviation is the square root of the variance, √49 = 7."),
    tf(c, "The variance of a data set is expressed in the same units as the original data.", False,
       "Variance is in squared units (for example, dollars²). The standard deviation takes the square root to return to the original units."),
    mc(c, "Two classes both average 75 on an exam. Class A has a standard deviation of 3 and class B has a standard deviation of 12. Which statement is true?",
       "Class B's scores are more spread out around the mean than class A's scores",
       ["Class A's scores are more spread out around the mean than class B's scores",
        "Class B must have the higher median, because its standard deviation is larger",
        "The two classes have identical score distributions, because their means match"],
       "A larger standard deviation means the values sit farther from the mean on average."),
    mc(c, "In a histogram of retirement ages, most people retire near 65, but a few retire in their 40s. Which skew describes this distribution?",
       "negative (left) skew", ["positive (right) skew", "no skew at all", "uniform skew"],
       "The long tail points toward the low values on the left, which is negative skew. It pulls the mean below the median."),
    mc(c, "Household income is strongly right-skewed. Which ordering of the three averages is typical?",
       "mean > median > mode",
       ["mean < median < mode", "median > mean > mode", "mean = median = mode"],
       "A few very large incomes drag the mean to the right of the median, and the mode sits lowest."),
    tf(c, "In a perfectly symmetric distribution, the mean and the median are equal.", True,
       "Symmetry puts the center of balance (the mean) and the middle value (the median) at the same point."),
    fb(c, "The spread measure calculated as Q3 minus Q1 is called the interquartile ___.",
       ["range"], "The interquartile range (IQR) is the spread of the middle 50% of the data."),
    mt(c, "Match each statistic to how it is calculated or what it describes.",
       [("Mean", "The sum of the values divided by how many there are"),
        ("Median", "The middle value once the data are sorted"),
        ("Mode", "The value that occurs most frequently"),
        ("Variance", "The average squared distance from the mean"),
        ("Standard deviation", "The square root of the variance"),
        ("IQR", "The distance between the first and third quartiles")],
       "Mean, median and mode describe the center; variance, standard deviation and IQR describe the spread."),
]))

# ======================================================================= 2
c = "Random Variables & Distributions"
SECTIONS.append(("2. Random Variables and Distributions", [
    mc(c, "A random variable is best described as ___.",
       "a variable whose numeric value is determined by the outcome of a random process",
       ["a variable whose value is chosen by the researcher before any data are collected",
        "a variable that can take only the values 0 or 1 on each trial of an experiment",
        "a variable whose value changes every time the program that uses it is run"],
       "Examples: the number of heads in 10 flips, or the time until the next customer arrives."),
    mc(c, "Which of these is a DISCRETE random variable?",
       "the number of customers who enter a store in one hour",
       ["the time a customer spends waiting in the checkout line",
        "the weight of the groceries in a customer's shopping bag",
        "the temperature inside the store at noon on a given day"],
       "Customers are counted in whole numbers. Time, weight and temperature can take any value in a range, so they are continuous."),
    mc(c, "Which of these is a CONTINUOUS random variable?",
       "the time it takes a runner to finish a race",
       ["the number of runners who finish a race within an hour",
        "the number of laps a runner completes before stopping",
        "the finishing place (1st, 2nd, 3rd...) of a particular runner"],
       "Time can take any value in an interval (12.4 s, 12.43 s, ...). The others are counts or ranks."),
    tf(c, "A random variable that can take any value within an interval, such as a height, is continuous.", True,
       "Continuous variables are measured; discrete variables are counted."),
    mc(c, "Which statement describes a normal distribution?",
       "It is symmetric and bell-shaped, with the mean, median and mode at the center",
       ["It is flat, with every value in the range equally likely to occur",
        "It is skewed to the right, with the mean larger than the median",
        "It counts the successes in a fixed number of yes-or-no trials"],
       "The normal distribution is the continuous bell curve. Flat is uniform; success counts are binomial."),
    mc(c, "Adult heights are normally distributed with a mean of 170 cm and a standard deviation of 10 cm. About what percentage of adults are between 150 cm and 190 cm tall?",
       "about 95%", ["about 68%", "about 99.7%", "about 50%"],
       "150 and 190 are two standard deviations below and above the mean. Empirical rule: about 95% fall within two."),
    mc(c, "Exam scores are normally distributed with a mean of 70 and a standard deviation of 8. About what share of students score between 62 and 78?",
       "about 68%", ["about 95%", "about 50%", "about 99.7%"],
       "62 and 78 are exactly one standard deviation below and above the mean, so about 68% fall between them."),
    mc(c, "Which situation is modeled by a binomial distribution?",
       "the number of defective bulbs in a random batch of 25, where each bulb is defective or not",
       ["the number of emails that arrive in a one-hour interval during the work day",
        "the height of one adult selected at random from a large population",
        "the number showing on a single roll of a fair six-sided die"],
       "Binomial: a fixed number of independent trials, each with two outcomes and the same chance of success."),
    mc(c, "Which situation is modeled best by a Poisson distribution?",
       "the number of customer calls received by a help desk in one hour",
       ["the number of heads that appear in 10 flips of a fair coin",
        "the height of one student chosen at random from the campus",
        "the face that shows on a single roll of a fair six-sided die"],
       "Poisson counts how many events occur in a fixed interval of time or space."),
    mc(c, "A random number generator returns a value between 0 and 1, and every value in that range is equally likely. The values follow a ___ distribution.",
       "uniform", ["normal", "binomial", "Poisson"],
       "A uniform distribution gives every value in its range the same likelihood, so its graph is flat."),
    mc(c, "Which of these is NOT a requirement for a binomial experiment?",
       "each trial must have more than two possible outcomes",
       ["the experiment has a fixed number of trials", "each trial is independent of the others",
        "the chance of success is the same on every trial"],
       "A binomial trial has exactly two outcomes, success or failure."),
    tf(c, "A Poisson random variable is continuous.", False,
       "It counts events, so it takes whole-number values and is discrete."),
    mt(c, "Match each distribution to the situation it describes.",
       [("Normal", "Adult heights clustered symmetrically around an average"),
        ("Binomial", "The number of successes in a fixed number of yes-or-no trials"),
        ("Poisson", "The number of events occurring in a fixed interval of time"),
        ("Uniform", "Every value in a range is equally likely to occur")],
       "Normal and uniform are continuous; binomial and Poisson are discrete."),
    mc(c, "A histogram is used to show ___.",
       "the frequency distribution of a numeric variable grouped into bins",
       ["the relationship between two numeric variables across many observations",
        "the proportion that each category contributes to a whole",
        "the median and the quartiles of a single numeric variable"],
       "A histogram counts how many values fall in each range of a numeric variable."),
    tf(c, "Choosing very few bins for a histogram can hide features of the data, such as two separate peaks.", True,
       "Bin width changes how the shape looks. Too few bins smooth detail away; too many make the plot noisy."),
    mc(c, "The bars of a histogram touch each other, but the bars of a bar chart are usually separated. Why?",
       "A histogram's bins are consecutive ranges of a numeric scale, while bar-chart bars are separate categories",
       ["A histogram shows percentages, while a bar chart can show only raw counts",
        "A histogram is always drawn horizontally, while a bar chart is drawn vertically",
        "A histogram always has exactly ten bins, while a bar chart can have any number"],
       "The touching bars signal a continuous scale with no gaps between the ranges."),
]))

# ======================================================================= 3
c = "Inferential Statistics"
SECTIONS.append(("3. Inferential Statistics", [
    mc(c, "A 95% confidence interval for a population mean is 48 to 56. Which interpretation is best?",
       "We are 95% confident that the interval captures the true population mean",
       ["95% of all the individual values in the population lie between 48 and 56",
        "There is a 95% chance that the sample mean falls between 48 and 56",
        "The true mean has a 95% chance of being exactly 52, the center of the interval"],
       "The 95% describes the method: intervals built this way capture the true mean about 95% of the time."),
    mc(c, "Which change makes a confidence interval NARROWER, all else being equal?",
       "increasing the sample size",
       ["increasing the confidence level", "increasing the standard deviation of the data", "decreasing the sample size"],
       "More data means a more precise estimate. A higher confidence level or more variability makes the interval wider."),
    mc(c, "With the same data, moving from a 90% to a 99% confidence level makes the interval ___.",
       "wider", ["narrower", "unchanged", "shifted left"],
       "To be more confident of capturing the parameter, you have to accept a wider range."),
    mc(c, "Why do researchers calculate a minimum sample size before collecting data?",
       "To make sure the sample is large enough to estimate the parameter with acceptable precision",
       ["To guarantee that the sample mean will equal the population mean exactly",
        "To avoid having to run any hypothesis test on the data once it is collected",
        "To make sure that the data will follow a normal distribution when plotted"],
       "A sample that is too small gives wide intervals and unreliable results."),
    mc(c, "In hypothesis testing, the null hypothesis typically states that ___.",
       "there is no effect or no difference",
       ["the effect is as large as the researcher expects it to be",
        "the sample size is too small to draw any firm conclusion",
        "the alternative hypothesis has already been proven to be true"],
       "The null is the default claim that the test tries to find evidence against."),
    mc(c, "A hypothesis test returns p = 0.03 at a significance level of α = 0.05. What is the correct decision?",
       "Reject the null hypothesis, because p is less than α",
       ["Fail to reject the null hypothesis, because p is greater than zero",
        "Accept the null hypothesis as proven, because p is a small number",
        "Reject the alternative hypothesis, because p is below 0.05"],
       "When p < α the result is statistically significant, so you reject the null."),
    mc(c, "A hypothesis test returns p = 0.20 at a significance level of α = 0.05. What is the correct conclusion?",
       "Fail to reject the null hypothesis; the evidence is not strong enough",
       ["Reject the null hypothesis, because 0.20 is larger than 0.05",
        "Accept the alternative hypothesis, because p is not equal to zero",
        "Prove the null hypothesis true, because p is a long way from 0.05"],
       "p > α means the data are consistent with the null. That is not proof the null is true."),
    mc(c, "Which statement best defines a p-value?",
       "The probability of results at least this extreme if the null hypothesis were true",
       ["The probability that the null hypothesis is true, given the data collected",
        "The probability that the alternative hypothesis is true, given the data collected",
        "The proportion of the sample that falls inside the confidence interval"],
       "A small p-value says the observed data would be surprising if the null were true."),
    mc(c, "Rejecting a null hypothesis that is actually true is called a ___.",
       "Type I error", ["Type II error", "standard error", "systematic error"],
       "Type I = false positive. Its probability is the significance level α."),
    mc(c, "Failing to reject a null hypothesis that is actually false is called a ___.",
       "Type II error", ["Type I error", "standard error", "sampling error"],
       "Type II = false negative: a real effect goes undetected."),
    mc(c, "A drug trial concludes that a drug works, when in truth it has no effect. Which error occurred?",
       "Type I error (a false positive)",
       ["Type II error (a false negative)", "Sampling error (the sample was too small)", "No error, because the test result was significant"],
       "The null (no effect) was true but was rejected, so it is a Type I error."),
    mc(c, "The significance level α is the probability of making a ___.",
       "Type I error", ["Type II error", "sampling error", "rounding error"],
       "Choosing α = 0.05 accepts a 5% chance of rejecting a true null."),
    mc(c, "Which test is typically used to compare a sample mean to a target value when the population standard deviation is unknown and the sample is small?",
       "t-test", ["z-test", "F-test", "Poisson test"],
       "The t-test uses the sample's own standard deviation and the t distribution, which handles small samples."),
    mc(c, "A z-test is appropriate when ___.",
       "the population standard deviation is known and the sample is reasonably large",
       ["the data are categorical, with more than two labels for each value",
        "the population standard deviation is unknown and the sample has 10 values",
        "the variable that is being measured can only take whole-number values"],
       "z-tests rely on a known σ (or a large n); otherwise the t-test is the safer choice."),
    mc(c, "A value of 86 comes from a distribution with a mean of 70 and a standard deviation of 8. What is its z-score?",
       "2", ["16", "1.5", "8"],
       "z = (86 − 70) / 8 = 2."),
    mc(c, "A student's z-score on a test is −1. What does that tell you?",
       "Their score is one standard deviation below the mean",
       ["Their score is one point below the mean score of the class",
        "Their score is one standard deviation above the mean score",
        "Their score is one percent below the average of the class"],
       "A z-score gives distance from the mean in standard deviations; the sign gives the direction."),
    tf(c, "A z-score tells you how many standard deviations a value is from the mean.", True,
       "z = (value − mean) / standard deviation."),
    sa(c, "A company tests whether a new training program changes employee productivity. Explain what a Type I error and a Type II error would mean in this situation, and say which one the significance level α controls.",
       "The null hypothesis is that the program has no effect on productivity.\n\nA Type I error means rejecting a true null: concluding the program changes productivity when it really does nothing (a false positive). The significance level α is the probability of making this error, so choosing α = 0.05 accepts about a 5% risk of it.\n\nA Type II error means failing to reject a false null: concluding there is no evidence of an effect when the program really does change productivity (a false negative).",
       ["Says the null hypothesis is 'no effect' (or no difference)",
        "Describes a Type I error as rejecting a true null, or finding an effect that is not there",
        "Describes a Type II error as failing to reject a false null, or missing a real effect",
        "States that α is the probability of a Type I error"],
       "Type I = false alarm, Type II = missed detection."),
]))

# ======================================================================= 4
c = "Outliers & Choosing a Plot"
SECTIONS.append(("4. Outliers and Choosing a Plot", [
    mc(c, "A data set has Q1 = 12 and Q3 = 30. Using the 1.5 × IQR rule, which of these values is an outlier?",
       "60", ["50", "-10", "30"],
       "IQR = 18, so the fences are 12 − 27 = −15 and 30 + 27 = 57. Only 60 lies outside them."),
    mc(c, "By the common z-score rule, a value is flagged as an outlier when it lies more than ___ standard deviations from the mean.",
       "3", ["1", "2", "5"],
       "In a normal distribution 99.7% of the values are within 3 standard deviations, so anything beyond is unusual."),
    mc(c, "A value has a z-score of −3.4. Under the z-score rule, what is it?",
       "an outlier, because it is more than 3 standard deviations below the mean",
       ["an ordinary value, because it is below the mean rather than above the mean",
        "an outlier only if the value is also greater than the median of the data",
        "invalid data that has to be deleted from the data set before analysis"],
       "The sign gives direction only. What matters is that |z| is larger than 3."),
    mc(c, "In a box-whisker plot, the box spans from ___.",
       "Q1 to Q3", ["the minimum to the maximum", "the mean minus to the mean plus one SD", "the 5th to the 95th percentile"],
       "The box covers the middle 50% of the data, and the line inside it is the median."),
    mc(c, "In a box-whisker plot, individual points drawn beyond the ends of the whiskers represent ___.",
       "potential outliers", ["the mean and the median", "the first and third quartiles", "missing values"],
       "Whiskers reach the farthest values within 1.5 × IQR of the box; anything past that is plotted as a dot."),
    mc(c, "Which is a reasonable first step when you find an outlier in your data?",
       "Investigate whether it is a data-entry error or a real but unusual observation",
       ["Delete it immediately, since outliers are always mistakes in the data",
        "Replace it with the mean without checking anything else about the row",
        "Ignore it, because outliers never change a statistic such as the mean"],
       "Errors should be fixed, but real extreme values can carry important information."),
    mc(c, "Which plot best shows how a company's monthly sales changed over two years?",
       "line plot", ["pie chart", "box-whisker plot", "histogram"],
       "A line plot shows a trend over an ordered sequence such as time."),
    mc(c, "Which chart best shows what share of a budget goes to each of five spending categories?",
       "pie chart", ["scatter plot", "line plot", "histogram"],
       "A pie chart shows parts of a whole."),
    mc(c, "Which plot is best for checking the shape of the distribution of exam scores?",
       "histogram", ["pie chart", "scatter plot", "bar chart of student names"],
       "A histogram bins the numeric scores so you can see skew, peaks and spread."),
    mc(c, "Which plot best shows whether taller people tend to be heavier?",
       "scatter plot", ["histogram", "pie chart", "line plot over time"],
       "A scatter plot places each (height, weight) pair, revealing any trend or correlation."),
    mc(c, "A bar chart is best used to ___.",
       "compare values across separate categories",
       ["show how one variable changes continuously over time",
        "reveal the shape of the distribution of a numeric variable",
        "display the quartiles and the outliers of a numeric variable"],
       "Each bar is one category (a department, a product); a histogram or box plot handles distributions."),
    mt(c, "Match each plot to what it is best at showing.",
       [("Histogram", "The shape of a numeric distribution"),
        ("Scatter plot", "The relationship between two numeric variables"),
        ("Line plot", "A trend over time or an ordered sequence"),
        ("Box-whisker plot", "The median, quartiles and outliers"),
        ("Bar chart", "A comparison across categories"),
        ("Pie chart", "The parts that make up a whole")],
       "Choose the plot from the question you are asking of the data."),
]))

# ======================================================================= 5
c = "NumPy"
SECTIONS.append(("5. NumPy", [
    mc(c, "Which line imports NumPy using the standard alias?",
       "import numpy as np", ["import NumPy as np", "from np import numpy", "using numpy as np"],
       "Python is case-sensitive: the module is numpy, conventionally shortened to np."),
    mc(c, "A NumPy array has the shape (5, 3). How many elements does it hold, and how many dimensions does it have?",
       "15 elements and 2 dimensions",
       ["8 elements and 2 dimensions", "15 elements and 1 dimension", "15 elements and 3 dimensions"],
       "The size is rows × columns = 5 × 3 = 15. A shape with two numbers means a 2-D array; ndim is the length of the shape."),
    mc(c, "Which call creates an array of zeros with 3 rows and 2 columns?",
       "np.zeros((3, 2))", ["np.zeros((2, 3))", "np.zeros(6)", "np.zeros([3], [2])"],
       "The shape is given as one tuple, (rows, columns). np.zeros(6) is a flat array of six zeros."),
    mc(c, "What does np.zeros((4, 3)).ndim return?",
       "2", ["3", "4", "12"],
       "ndim counts the dimensions (axes), not the elements. A rows-and-columns array has 2."),
    mc(c, "What does np.zeros(5) create?",
       "a one-dimensional array holding five 0.0 values",
       ["a one-dimensional array holding five 1.0 values",
        "a five-by-five array in which every value is zero",
        "an empty array that is waiting to be filled with values"],
       "zeros(n) gives n zeros (as floats). For a grid, pass a shape tuple such as np.zeros((5, 5))."),
    mc(c, "How many elements does np.arange(3, 30, 6) create?",
       "5", ["4", "6", "9"],
       "It produces 3, 9, 15, 21, 27, and stops before 30. The stop value is never included."),
    mc(c, "What does np.random.random((3, 2)) create?",
       "a 3-by-2 array of random floats between 0 and 1",
       ["a 3-by-2 array of random whole numbers between 0 and 10",
        "a 2-by-3 array of random floats between 0 and 1",
        "a single random float that is somewhere between 0 and 3"],
       "The argument is a shape tuple (rows, columns); the values are drawn from [0, 1)."),
    mc(c, "If a = np.array([1, 2, 3]), what does a * 2 return?",
       "[2 4 6]", ["[1 2 3 1 2 3]", "[1 2 3 2]", "[3 4 5]"],
       "NumPy arithmetic is element by element. Only an ordinary Python list repeats when you multiply it."),
    mc(c, "What does the expression [1, 2, 3] * 2 return for an ordinary Python list?",
       "[1, 2, 3, 1, 2, 3]", ["[2, 4, 6]", "[1, 2, 3, 2]", "an error"],
       "A list repeats under *. This is one reason to convert to an ndarray before doing math."),
    mc(c, "For a = np.array([[1, 2], [3, 4]]), what does a.sum(axis=0) return?",
       "[4 6]", ["[3 7]", "10", "[2 6]"],
       "axis=0 collapses the rows, giving one total per column: 1 + 3 = 4 and 2 + 4 = 6."),
    mc(c, "For a = np.array([[1, 2], [3, 4]]), what does a.mean() return?",
       "2.5", ["2.0", "10", "4"],
       "With no axis, the mean is taken over all four elements: 10 / 4 = 2.5."),
    mc(c, "What does np.corrcoef(x, y) return?",
       "a 2×2 correlation matrix, where the off-diagonal value is the correlation between x and y",
       ["a single number between 0 and 1 that gives the strength of the relationship",
        "a list of the covariance values for each pair of elements in x and y",
        "an array of the z-scores for each of the values in x and in y"],
       "The diagonal is each variable correlated with itself (1.0); read x-versus-y from either off-diagonal cell."),
    mc(c, "What does np.percentile(data, 90) return?",
       "the value below which about 90% of the data fall",
       ["the 90th value in the data once it has been sorted",
        "ninety percent of the largest value found in the data",
        "the mean of the top 90% of the values in the data"],
       "A percentile is a position in the distribution, not an index or a fraction of the maximum."),
    tf(c, "np.array([1, 2.5, 3]) stores every element as the same data type.", True,
       "ndarrays are homogeneous. The integers are upcast, so all three values are float64."),
    tf(c, "A NumPy array can hold integers, strings and floats while keeping each element's own type.", False,
       "An ndarray has a single dtype. A mix of numbers and strings is converted to one type, here strings."),
    mc(c, "Why are NumPy arrays usually faster than Python lists for numeric work?",
       "They store same-type values in one block of memory and operate on them in compiled code",
       ["They store the values as text, which the computer is able to read faster",
        "They automatically spread every operation across several separate computers",
        "They skip the checking of data types so that each step does less work"],
       "Homogeneous, contiguous storage plus vectorized compiled loops is what makes them fast and compact."),
    fb(c, "Complete the call that creates a 2 by 3 array filled with zeros: np.______((2, 3))",
       ["zeros"], "np.zeros takes a shape tuple. np.ones is the same idea with 1.0 values."),
]))

# ======================================================================= 6
c = "pandas: Series, DataFrames & Selection"
SECTIONS.append(("6. pandas: Selecting and Summarizing Data", [
    mc(c, "What is a pandas Series?",
       "A one-dimensional labeled array of values with an index",
       ["A two-dimensional table of labeled rows and labeled columns",
        "A fixed-length list of numbers that has no labels attached",
        "A sequence of DataFrames that all share one common index"],
       "A Series is one labeled column of data; a DataFrame is a table of Series sharing an index."),
    mc(c, "What is a pandas DataFrame?",
       "A two-dimensional labeled table whose columns can hold different data types",
       ["A one-dimensional array whose values must all share the same data type",
        "A Python dictionary that cannot be changed after it has been created",
        "A chart that displays the values stored in a table of data"],
       "Unlike an ndarray, each DataFrame column can have its own dtype."),
    mc(c, "Each individual column of a DataFrame is a ___.",
       "Series", ["ndarray with no index", "dictionary", "tuple"],
       "df['col'] returns a Series that shares the DataFrame's index."),
    mc(c, EMP + "What does emp.iloc[2]['name'] return?",
       "Cy", ["Ben", "Dee", "IT"],
       "iloc[2] is the row at position 2 (IT, Cy, 75000, 5); its name is Cy."),
    mc(c, EMP + "Which rows does emp.iloc[1:3] return?",
       "the rows at positions 1 and 2 (Ben and Cy)",
       ["the rows at positions 1, 2 and 3 (Ben, Cy and Dee)",
        "the rows at positions 0, 1 and 2 (Ana, Ben and Cy)",
        "only the row at position 3, which is the row for Dee"],
       "iloc slices like a Python list: the start is included and the stop is excluded."),
    mc(c, EMP + "Which rows does emp.loc[1:3] return?",
       "the rows labeled 1, 2 and 3, because loc includes the end label",
       ["the rows labeled 1 and 2, because loc excludes the end label",
        "only the row labeled 3, because loc picks just one row at a time",
        "an error, because loc cannot take a slice of row labels"],
       "loc is label-based and, unlike iloc, includes both endpoints of a slice."),
    mc(c, "Which pair correctly completes this sentence? In pandas, loc selects by ___ and iloc selects by ___.",
       "label; integer position", ["integer position; label", "row; column", "name; data type"],
       "Use loc when you know the index label, iloc when you know the numeric position."),
    tf(c, "The older ix indexer has been removed from current pandas; loc and iloc replace it.", True,
       "ix mixed label and position lookups, which was ambiguous. Use loc or iloc instead."),
    mc(c, EMP + "Which code selects the rows where salary is greater than 60000?",
       "emp[emp['salary'] > 60000]",
       ["emp['salary' > 60000]", "emp.where(salary > 60000)", "emp[salary > 60000]"],
       "A boolean mask: the inner comparison gives True/False for each row, and the outer brackets keep the True rows."),
    mc(c, EMP + "How many rows does emp[emp['years'] >= 6] return?",
       "3", ["2", "4", "6"],
       "years of 7, 9 and 6 meet the condition (Ben, Dee and Fay)."),
    mc(c, EMP + "Which code returns the employees in the IT department who earn more than 80000?",
       "emp[(emp['dept'] == 'IT') & (emp['salary'] > 80000)]",
       ["emp[emp['dept'] == 'IT' and emp['salary'] > 80000]",
        "emp[(emp['dept'] == 'IT'), (emp['salary'] > 80000)]",
        "emp[emp['dept'] == 'IT' & emp['salary'] > 80000]"],
       "Combine masks with & and wrap each comparison in parentheses; the word and does not work on Series."),
    mc(c, "How does emp.where(emp['salary'] > 60000) differ from emp[emp['salary'] > 60000]?",
       "where keeps every row and puts NaN where the condition is False, while the mask drops those rows",
       ["where drops the rows where the condition is False, while the mask keeps all rows and fills NaN",
        "where works only on a Series, while the mask works only on a whole DataFrame object",
        "They are identical in both shape and content, so either one can be used"],
       "where preserves the shape of the original; boolean masking returns only the matching rows."),
    mc(c, "Which code is equivalent to emp[emp['salary'] > 60000]?",
       "emp.query('salary > 60000')",
       ["emp.query(salary > 60000)", "emp.filter('salary > 60000')", "emp.query['salary > 60000']"],
       "query() takes the condition as a string and returns a new DataFrame of the matching rows."),
    mc(c, EMP + "What does emp.query(\"dept == 'IT' and years > 6\") return?",
       "only Dee's row",
       ["both Cy's row and Dee's row", "Ben's row and Dee's row", "an error, because query cannot use the word and"],
       "Both conditions must hold: IT employees are Cy (5 years) and Dee (9 years); only Dee has more than 6. Inside query(), and works."),
    mc(c, EMP + "What does emp.tail(2) return?",
       "the last two rows (Eli and Fay)",
       ["the first two rows (Ana and Ben)", "the last two columns of the DataFrame", "every row except the last two"],
       "head(n) gives the first n rows and tail(n) the last n; the default for both is 5."),
    mc(c, EMP + "What does emp['dept'].value_counts() show?",
       "how many rows have each department: Sales 2, IT 2, HR 2",
       ["the number of non-null values in the column, which is 6",
        "the unique department names only, without any counts",
        "the total salary for each of the departments in the table"],
       "value_counts() lists each unique value with its frequency; count() would give just the single total."),
    mc(c, "Which code returns the number of rows for every unique combination of the columns 'city' and 'plan' in df?",
       "df.groupby(['city', 'plan']).size()",
       ["df[['city', 'plan']].unique()", "df.groupby('city', 'plan').count()", "df['city', 'plan'].size()"],
       "Group by both columns (as a list) and take size() to count the rows in each group."),
    mc(c, EMP + "What does emp.shape return?",
       "(6, 4)", ["(4, 6)", "24", "6"],
       "shape is an attribute giving (rows, columns). size would be 24."),
    mc(c, "In pandas, axis=1 refers to ___.",
       "the columns, so the operation runs across each row",
       ["the rows, so the operation runs down each column", "the index labels only, and not the data", "the DataFrame as a whole, in a single result"],
       "axis=0 works down the rows (one result per column); axis=1 works across the columns (one result per row)."),
    mc(c, EMP + "What does emp[['salary', 'years']].sum(axis=1) compute?",
       "the sum of salary and years for each row",
       ["the sum of each column, giving one result per column",
        "a single grand total of both columns combined together",
        "the sum of the index labels for each of the rows"],
       "axis=1 adds across the columns within each row, so it returns one value per row."),
    mc(c, "Which statistics does df.describe() report for a numeric column by default?",
       "count, mean, standard deviation, minimum, quartiles and maximum",
       ["mean, mode, variance, skewness and range for the column",
        "count, median, mode, sum and variance for the column",
        "mean, correlation, p-value and R-squared for the column"],
       "describe() gives count, mean, std, min, 25%, 50%, 75% and max. It has no mode or variance row."),
    mc(c, "By default, pandas df.std() and df.var() compute the ___.",
       "sample standard deviation and variance (dividing by n − 1)",
       ["population standard deviation and variance (dividing by n)",
        "median absolute deviation and the range of each column",
        "standard error and confidence interval of each column"],
       "pandas uses ddof=1. NumPy's np.std and np.var default to dividing by n."),
    mc(c, "What does df.count() return?",
       "the number of non-null values in each column",
       ["the total number of rows in the DataFrame", "the number of unique values in each column", "the number of columns in the DataFrame"],
       "count() ignores missing values, so a column with NaNs reports fewer than the number of rows."),
]))

# ======================================================================= 7
c = "Manipulating & Cleaning Data"
SECTIONS.append(("7. Manipulating and Cleaning Data", [
    fb(c, "Complete the call that loads a CSV file into a DataFrame: df = pd.______('sales.csv')",
       ["read_csv"], "pd.read_csv() reads a comma-separated file into a DataFrame."),
    mc(c, "Which call reads a pickled file named data.pkl into a DataFrame?",
       "pd.read_pickle('data.pkl')",
       ["pd.read_pkl('data.pkl')", "pd.load_pickle('data.pkl')", "pd.open_pickle('data.pkl')"],
       "Pickle files use read_pickle, and DataFrame.to_pickle() writes them."),
    mc(c, "Which code adds a column named bonus, equal to 10% of salary, to emp?",
       "emp['bonus'] = emp['salary'] * 0.10",
       ["emp.add_column('bonus', emp['salary'] * 0.10)", "emp['bonus'] == emp['salary'] * 0.10", "emp.bonus() = emp['salary'] * 0.10"],
       "Assigning to a new column name creates the column. Note the single = for assignment."),
    mc(c, "Does emp.rename(columns={'salary': 'pay'}) change emp itself?",
       "No, it returns a new DataFrame unless you assign the result or pass inplace=True",
       ["Yes, rename always modifies emp directly and then returns nothing at all",
        "No, it works only on the row index labels, and not on the column names",
        "Yes, but only when the new column name is shorter than the old one"],
       "Most pandas methods return a new object. Assign it back: emp = emp.rename(...)."),
    mc(c, "Which code removes the column years from emp and returns a new DataFrame?",
       "emp.drop(columns=['years'])",
       ["emp.drop(['years'])", "emp.remove('years')", "emp.delete(columns='years')"],
       "drop(['years']) with no axis looks for a row labeled 'years' and raises a KeyError."),
    mc(c, "Which call adds the columns of df2 to df1, matching rows on a shared key column named id?",
       "pd.merge(df1, df2, on='id')",
       ["pd.concat([df1, df2], on='id')", "df1.append(df2, on='id')", "pd.stack(df1, df2, on='id')"],
       "merge combines tables side by side on a key, much like a SQL join."),
    mc(c, "By default, df1.join(df2) matches rows using ___.",
       "the index of both DataFrames",
       ["the first column of each DataFrame", "any columns that have the same name in both", "the row position, after sorting both tables"],
       "join() aligns on the index. Matching on shared column names is what merge() does by default."),
    mc(c, "Which code stacks the rows of df2 underneath df1, when both have the same columns?",
       "pd.concat([df1, df2])",
       ["pd.concat(df1, df2)", "pd.merge(df1, df2)", "df1.join(df2)"],
       "concat takes a list of DataFrames. Passing them as two separate arguments is an error."),
    mc(c, "When you stack two DataFrames with pd.concat and both use index labels 0, 1, 2, what happens to the labels?",
       "The repeated labels are kept unless you pass ignore_index=True",
       ["The repeated labels are renumbered automatically by concat", "The duplicate rows are dropped automatically by concat", "pandas raises an error whenever a label repeats"],
       "concat only stacks. Use ignore_index=True for a fresh 0..n-1 index, and drop_duplicates() to remove repeated rows."),
    mc(c, "Which code removes duplicate rows from df?",
       "df.drop_duplicates()",
       ["df.drop_unique()", "df.remove_duplicates()", "df.duplicated()"],
       "duplicated() only reports which rows are repeats, as True/False; drop_duplicates() removes them."),
    mc(c, "What does df.isna().sum().sum() return?",
       "the total number of missing values in the whole DataFrame",
       ["the number of columns that contain at least one missing value",
        "the number of rows that contain at least one missing value",
        "the sum of all of the values that are not missing in the table"],
       "isna() gives a True/False table; the first sum() counts Trues per column and the second adds those counts up."),
    mc(c, "What does df.dropna(axis=1) do?",
       "drops every column that contains at least one missing value",
       ["drops every row that contains at least one missing value",
        "drops every column that is made up entirely of numeric values",
        "fills each missing value with the value from the previous column"],
       "The default dropna() drops rows; axis=1 switches it to columns."),
    mc(c, "What is imputation?",
       "Replacing missing values with substitute values estimated from the data",
       ["Deleting every row that contains a missing value from the data set",
        "Converting text columns into numeric columns before running an analysis",
        "Combining two DataFrames that share a common key column"],
       "Imputing keeps the row but fills the gap, for example with the mean or with a neighboring value."),
    mc(c, "Which code fills the missing values in the salary column with that column's mean?",
       "emp['salary'].fillna(emp['salary'].mean())",
       ["emp['salary'].fillna('mean')", "emp['salary'].fillna(method='mean')", "emp['salary'].fill(emp.mean())"],
       "fillna() takes the replacement value, so compute the mean first and pass it in."),
    mc(c, "For the series 5, NaN, 8, which statement is correct?",
       "ffill gives 5, 5, 8 and bfill gives 5, 8, 8",
       ["ffill gives 5, 8, 8 and bfill gives 5, 5, 8", "ffill and bfill both give 5, 6.5, 8", "ffill gives 5, 0, 8 and bfill gives 5, 0, 8"],
       "Forward fill carries the last valid value forward; backward fill pulls the next valid value back."),
    mc(c, "Daily prices are missing for one holiday between two valid trading days. Which fill strategy is most defensible?",
       "Forward fill, since prices tend to carry over from the previous valid day",
       ["Fill with 0, since no trading took place on that day",
        "Drop the whole price column, since it contains a gap in the data",
        "Fill with the most common price found across all of the dates"],
       "A 0 would look like a crash. Carrying the last value forward is a common, explainable choice for ordered data."),
    mc(c, "What is a drawback of filling every missing value in a column with that column's mean?",
       "It shrinks the variance of the column and can hide real variation in the data",
       ["It always increases the number of rows in the DataFrame",
        "It changes the data type of the whole column into text",
        "It makes the mean of the column differ from its original mean"],
       "The mean is unchanged, but the filled values all sit at the center, so the spread looks smaller than it is."),
    mc(c, "After df = pd.read_csv('data.csv'), what type of object is df?",
       "a DataFrame", ["a Series", "an ndarray", "a list of dictionaries"],
       "read_csv returns a DataFrame, with the column names taken from the file's header row."),
    sa(c, "A DataFrame of patient records has missing values in the age column for 8% of the rows. Compare two ways of handling them: dropping the rows with dropna(), and filling them with the column mean using fillna(). Give one advantage and one disadvantage of each.",
       "dropna(): Advantage: simple, and no made-up values enter the data. Disadvantage: loses the other information in those rows and shrinks the sample, which can bias results if the missing ages are not random.\n\nfillna(mean): Advantage: keeps every row, so the other columns are still used and the sample size is preserved. Disadvantage: invents values that cluster at the mean, which reduces the variance and can weaken relationships with other variables.",
       ["Gives an advantage of dropna(), such as simplicity or no invented values",
        "Gives a disadvantage of dropna(), such as lost rows or a smaller sample",
        "Gives an advantage of mean-filling, such as keeping all rows",
        "Gives a disadvantage of mean-filling, such as reduced variance or distorted data"],
       "The best choice depends on how much is missing and why."),
]))

# ======================================================================= 8
c = "Indexes, Reshaping & Grouping"
SECTIONS.append(("8. Indexes, Reshaping and Grouping", [
    mc(c, "What does emp.set_index('name') do?",
       "Returns a DataFrame that uses the name column as its row index",
       ["Sorts the DataFrame alphabetically by the contents of the name column",
        "Renames the index of the DataFrame so that it is called name",
        "Removes the name column and discards the values that it held"],
       "The name column moves out of the data and becomes the row labels."),
    mc(c, "What does reset_index() do to a DataFrame whose index is currently the name column?",
       "Moves the index back into a regular column and restores a 0, 1, 2... index",
       ["Deletes the index and the name values from the DataFrame permanently",
        "Sorts the rows back into the original order of the source file",
        "Resets every value in the DataFrame to NaN and starts over"],
       "Add drop=True if you want to discard the old index instead of keeping it as a column."),
    mc(c, "A DataFrame created without specifying an index gets which kind of index by default?",
       "a RangeIndex of integers 0, 1, 2, ...",
       ["a MultiIndex built from the first two columns", "an index made up of the column names", "no index at all; rows are identified only by position"],
       "The default RangeIndex counts the rows from 0."),
    mc(c, "What is a MultiIndex?",
       "An index with two or more levels, such as region and product",
       ["Two separate DataFrames that happen to share the same index", "An index that contains repeated labels only", "A list of the column names in the DataFrame"],
       "set_index(['region', 'product']) builds one. Use unstack() to move a level into the columns."),
    mc(c, "Which code returns the mean salary of each department?",
       "emp.groupby('dept')['salary'].mean()",
       ["emp.groupby('salary')['dept'].mean()", "emp.mean('dept')['salary']", "emp['salary'].groupby().mean('dept')"],
       "Group by the category, select the column to summarize, then aggregate."),
    mc(c, EMP + "Which department has the highest mean salary?",
       "IT", ["Sales", "HR", "They are tied"],
       "IT: (75000 + 82000) / 2 = 78500. Sales: 56500. HR: 51500."),
    mc(c, "What does emp.groupby('dept')['salary'].agg(['min', 'max']) return?",
       "one row per department, with the minimum and maximum salary as two columns",
       ["one row per salary, with the department shown in two columns",
        "a single row holding the overall minimum and maximum salary",
        "one column per department, holding every salary for that department"],
       "agg() with a list applies each function to every group."),
    mc(c, "What does emp.pivot_table(index='dept', values='salary', aggfunc='max') return?",
       "the highest salary in each department, one row per department",
       ["the highest salary in the whole table, as a single number",
        "the total salary of each department, one row per department",
        "one row per employee, with the salary as the only column"],
       "index sets the rows, values picks the column, and aggfunc says how to summarize each group."),
    mc(c, "A DataFrame has two different rows with the same product and the same region. You call df.pivot(index='product', columns='region', values='sales'). What happens?",
       "It raises an error, because pivot cannot handle a repeated product-and-region pair",
       ["It adds the two sales values together, so that the cell holds their total",
        "It averages the two sales values, so that the cell holds their mean",
        "It keeps the first row it finds and quietly discards the second row"],
       "pivot only reshapes. pivot_table(..., aggfunc='sum') would combine the duplicates instead."),
    mc(c, "What does unstack() do on a DataFrame that has a two-level row index?",
       "Moves the innermost row-index level into the columns, making the table wider",
       ["Moves the column labels into a new row-index level, making the table longer",
        "Removes the duplicated labels from the index of the rows",
        "Splits the DataFrame into two separate DataFrames by level"],
       "stack() does the opposite: it pushes columns down into the row index."),
    mc(c, "Which operation turns the columns of a DataFrame into an innermost row-index level, making the table longer?",
       "stack()", ["unstack()", "pivot_table()", "describe()"],
       "stack() lengthens the table; unstack() and pivot_table() widen it."),
    fb(c, "To split rows into groups by a column and then summarize each group, use the DataFrame method df.______('column').",
       ["groupby"], "groupby() followed by an aggregate such as sum() or mean() is the pandas version of SQL's GROUP BY."),
    mt(c, "Match each pandas call to what it does.",
       [("set_index('id')", "Makes the id column the row index"),
        ("reset_index()", "Moves the index back into a column and renumbers the rows"),
        ("stack()", "Pivots columns into the innermost row-index level"),
        ("unstack()", "Pivots an index level out into the columns"),
        ("pivot_table()", "Reshapes the data while aggregating repeated entries"),
        ("groupby()", "Splits the rows into groups so each can be summarized")],
       "Reshaping calls change the table's layout; groupby changes what is being summarized."),
]))

# ======================================================================= 9
c = "Linear Regression"
SECTIONS.append(("9. Linear Regression", [
    mc(c, "A correlation coefficient of −0.9 between hours of TV watched and exam score indicates ___.",
       "a strong negative linear relationship",
       ["a weak negative linear relationship", "a strong positive linear relationship", "no linear relationship at all"],
       "The sign gives the direction and the size (close to 1 in magnitude) gives the strength."),
    mc(c, "A correlation coefficient close to 0 means ___.",
       "there is little or no linear relationship between the two variables",
       ["the two variables are exactly equal to each other in every row",
        "one variable causes the other variable to change by a small amount",
        "the data contain mostly missing values in both of the columns"],
       "Near 0 means a straight-line trend is absent; there could still be a curved relationship."),
    tf(c, "A high correlation between two variables proves that one of them causes the other.", False,
       "Correlation measures association only. A third variable, or coincidence, may explain it."),
    mc(c, "Which code returns a table of pairwise correlation coefficients for the numeric columns of df?",
       "df.corr()", ["df.correl()", "df.corrcoef()", "df.relate()"],
       "DataFrame.corr() returns the correlation matrix; corrcoef is a NumPy function, np.corrcoef."),
    mc(c, "What does R², reported by a model's score() method, measure?",
       "the proportion of the variation in the target that the model explains",
       ["the average squared distance between the predictions and the actual values",
        "the slope of the best-fit line drawn through the points of the data",
        "the probability that each prediction made by the model is correct"],
       "R² runs from 0 (explains nothing) to 1 (explains everything) for a good fit."),
    mc(c, "A model's R² on the test set is 0.82. Which interpretation is best?",
       "About 82% of the variation in the target is explained by the model's features",
       ["The model's predictions are exactly correct about 82% of the time",
        "The model's predictions are off by 82% of the actual value on average",
        "82% of the rows in the test set were used to train the model"],
       "R² is a share of variation explained, not an accuracy percentage."),
    mc(c, "What does mean squared error (MSE) measure?",
       "the average of the squared differences between the predicted and the actual values",
       ["the average of the actual values minus the predicted values, unsquared",
        "the square root of the average difference between the model's features",
        "the proportion of the rows that the model predicted exactly right"],
       "Squaring stops positive and negative errors cancelling and punishes large misses. Lower is better."),
    mc(c, "Model A has an MSE of 4 and model B has an MSE of 9, both on the same test data. Which statement is correct?",
       "Model A is better, because its predictions are closer to the actual values on average",
       ["Model B is better, because a higher error means that the model has learned more",
        "They are equally good, because MSE only reflects the size of the test set",
        "Neither can be compared, because MSE is only comparable with R-squared values"],
       "On the same data, the smaller MSE means smaller average error."),
    mc(c, "In a model that predicts a car's resale price from its age and mileage, the dependent variable is ___.",
       "resale price", ["age", "mileage", "age and mileage together"],
       "The dependent (target) variable is what you predict. Age and mileage are the independent variables (features)."),
    mc(c, "Another name for the independent variables in a regression model is ___.",
       "features", ["targets", "labels", "residuals"],
       "Features are the inputs (X); the target or label is the output (y)."),
    mc(c, "Which equation describes a MULTIPLE linear regression model?",
       "price = b0 + b1·sqft + b2·bedrooms",
       ["price = b0 + b1·sqft, which uses a single feature", "bedrooms = b0 + b1·sqft, which uses a single feature", "price = b0, a constant with no features at all"],
       "Multiple regression has two or more independent variables; simple regression has exactly one."),
    mc(c, "Which sequence describes the usual regression workflow in scikit-learn?",
       "Split into train and test sets, fit the model on the training set, then predict on the test set",
       ["Fit the model on the whole data set, then split it into train and test sets to predict",
        "Predict on the test set, then fit the model to the predictions that it made",
        "Fit the model on the test set, then use the training set to predict"],
       "The test set must stay unseen during fitting, or the score will look better than it really is."),
    mc(c, "Why is a data set split into training and test sets?",
       "To measure how well the model predicts data it was not fitted on",
       ["To make the model train faster by reducing the data that it reads",
        "To remove the outliers from the data before the model is fitted",
        "To balance the number of rows that are held in each of the columns"],
       "Performance on the training data alone would overstate how well the model generalizes."),
    mc(c, "train_test_split(X, y, test_size=0.25) is applied to 200 rows. How many rows go to the training set?",
       "150", ["50", "25", "175"],
       "25% of 200 is 50 test rows, which leaves 150 for training."),
    mc(c, "model.fit(df['sqft'], df['price']) raises an error. What is the likely fix?",
       "Pass the feature as a 2-D table, df[['sqft']], instead of the 1-D Series df['sqft']",
       ["Convert the price column into strings before the model is fitted",
        "Call model.predict() before calling model.fit() on the same data",
        "Drop every row of df that contains a duplicate value in it"],
       "scikit-learn expects X to be 2-D (rows × features), so use double brackets even for one feature."),
    mc(c, "What does model.predict(X_test) return?",
       "the model's predicted target values for the rows in X_test",
       ["the R-squared score for the rows in X_test", "the correlation between X_test and y_test", "the rows of X_test sorted by their predicted value"],
       "predict() returns y-hat values. score(X_test, y_test) is what compares them with the truth."),
    mc(c, "What is a heatmap of df.corr() used for?",
       "to see at a glance which pairs of variables are strongly correlated, using color",
       ["to display the distribution of a single variable by grouping it into bins",
        "to show how one variable changes over time by joining points with a line",
        "to compare the totals of several categories using bars of equal width"],
       "Each cell is one pair's correlation, colored by its strength and direction."),
    sa(c, "Explain the difference between simple linear regression and multiple linear regression. Then give a realistic question that multiple regression could answer, and name its dependent variable and its independent variables.",
       "Simple linear regression predicts one dependent (target) variable from ONE independent variable (feature), fitting a line y = mx + b. Multiple linear regression predicts one dependent variable from TWO OR MORE independent variables.\n\nExample: predicting a used car's resale price. The dependent variable is the resale price; the independent variables are the car's age, mileage and engine size.",
       ["Says simple regression uses one independent variable",
        "Says multiple regression uses two or more independent variables",
        "Gives a realistic example question",
        "Names the dependent variable and at least two independent variables for the example"],
       "Both predict a single target; they differ in how many features go in."),
    sa(c, "Describe the steps you would follow to build and evaluate a linear regression model in Python, from a DataFrame to a score. For each step, name the function or method you would use.",
       "1. Choose the features X (for example df[['sqft', 'age']]) and the target y (df['price']).\n2. Split the data with train_test_split(X, y, test_size=0.2) into training and test sets.\n3. Create the model, LinearRegression(), and fit it on the training data with model.fit(X_train, y_train).\n4. Predict with model.predict(X_test).\n5. Evaluate on the test set with model.score(X_test, y_test) (R²) or mean_squared_error(y_test, predictions).",
       ["Separates the features (X) from the target (y)",
        "Splits the data into training and test sets (train_test_split)",
        "Fits the model on the training data only (fit)",
        "Predicts on the test data (predict)",
        "Evaluates with R² (score) or mean squared error"],
       "The key idea is that the test data play no part in fitting."),
]))

# ======================================================================= 10
c = "Plotting Code"
SECTIONS.append(("10. Plotting with Matplotlib", [
    mc(c, "Which line displays the current Matplotlib figure?",
       "plt.show()", ["plt.display()", "plt.render()", "plt.print()"],
       "plot, hist, scatter and the rest only build the figure; show() draws it."),
    mc(c, "What does plt.plot(x, y) draw by default?",
       "a line connecting the (x, y) points in order",
       ["a scatter of separate points with no line between them", "a histogram of the x values and the y values", "a pie chart of the y values and their shares"],
       "Use plt.scatter for unconnected points."),
    mc(c, "Which code draws a histogram of the list scores using 8 bins?",
       "plt.hist(scores, bins=8)",
       ["plt.histogram(scores, bins=8)", "plt.bar(scores, bins=8)", "plt.plot(scores, bins=8)"],
       "The function is hist, and bins controls how many ranges the values are grouped into."),
    mc(c, "Which code draws a scatter plot with height on the x-axis and weight on the y-axis?",
       "plt.scatter(height, weight)",
       ["plt.scatterplot(height, weight)", "plt.points(height, weight)", "plt.hist(height, weight)"],
       "plt.scatter takes the x values first, then the y values."),
    mc(c, "Which sequence draws a scatter plot with a fitted line on top of it?",
       "plt.scatter(x, y), then plt.plot(x, y_pred), then plt.show()",
       ["plt.line(x, y), then plt.scatter(x, y_pred), then plt.show()",
        "plt.show(), then plt.scatter(x, y), then plt.plot(x, y_pred)",
        "plt.hist(x, y), then plt.plot(x, y_pred), then plt.show()"],
       "Both layers are added to the same figure before show() displays it."),
    mc(c, "Which code draws a box-whisker plot of the list scores?",
       "plt.boxplot(scores)", ["plt.box(scores)", "plt.whisker(scores)", "plt.hist(scores, box=True)"],
       "matplotlib's function is boxplot."),
    mc(c, "Which line labels the x-axis of the current plot as 'Height (in)'?",
       "plt.xlabel('Height (in)')",
       ["plt.label_x('Height (in)')", "plt.axis('Height (in)')", "plt.title_x('Height (in)')"],
       "xlabel and ylabel name the axes, and title names the whole plot."),
    mc(c, "In sns.heatmap(df.corr(), annot=True), what does annot=True do?",
       "writes each correlation value inside its cell",
       ["annotates the color bar with the R-squared of the model", "highlights only those cells that have values above 0.5", "adds a title that names the DataFrame being plotted"],
       "Without annot, you see only colors and have to read the values from the color bar."),
]))


# The final is comprehensive: add more questions on the importing, cleaning and
# statistics topics from earlier in the course.
from itd145_final_extra import extend  # noqa: E402

extend(SECTIONS, mc, tf, fb, mt, sa, EMP)
