"""Question pool for ITD 145 Exam 2. Built by build_itd145.py.

mc(core, category, question, correct, [wrong, wrong, wrong], explanation)
tf(core, category, statement, answer, explanation)
mt(core, category, question, [(left, right), ...], explanation)

The correct option is slotted into a rotating position so answers are spread
across A-D; the quiz UI shuffles again at runtime if it wants to.
"""

_n = [0]


def mc(core, cat, q, correct, wrongs, expl):
    assert len(wrongs) == 3, q
    pos = _n[0] % 4
    _n[0] += 1
    opts = list(wrongs)
    opts.insert(pos, correct)
    return {"core": core, "type": "mc", "category": cat, "question": q,
            "options": opts, "correct": pos, "explanation": expl}


def tf(core, cat, q, ans, expl):
    return {"core": core, "type": "tf", "category": cat, "question": q,
            "correct": ans, "explanation": expl}


def mt(core, cat, q, pairs, expl):
    return {"core": core, "type": "matching", "category": cat, "question": q,
            "pairs": [{"left": a, "right": b} for a, b in pairs], "explanation": expl}


Y, X = True, False  # core / extra

SECTIONS = []

# =========================================================================== NumPy
SECTIONS.append(("NumPy", [
    mc(Y, "NumPy", "What does the name NumPy stand for?",
       "Numerical Python", ["Number Pipeline", "New Multidimensional Python", "Numeric Pandas"],
       "NumPy is short for Numerical Python, the library for fast numeric arrays."),
    mc(Y, "NumPy", "Which statement imports NumPy using the standard community alias?",
       "import numpy as np", ["import np as numpy", "from numpy import *  as np", "include numpy as np"],
       "import <library> as <alias>. The convention is np for NumPy."),
    mc(Y, "NumPy", "What is a code library (module) in Python?",
       "A collection of pre-written code you bring into a program with import",
       ["A folder where your data files are stored", "A built-in data type for lists", "A program that runs Python code line by line"],
       "Libraries such as NumPy, pandas and matplotlib are imported so you can reuse their functions."),
    mc(X, "NumPy", "What is the purpose of the 'as' keyword in 'import pandas as pd'?",
       "It gives the imported library a shorter alias", ["It installs the library", "It makes the library run faster", "It imports only part of the library"],
       "The alias lets you write pd.DataFrame instead of pandas.DataFrame."),
    mc(Y, "NumPy", "What is an ndarray?",
       "NumPy's n-dimensional array, a grid of values that all share one data type",
       ["A Python list that can hold mixed types", "A pandas table with named columns", "A function that sorts numbers"],
       "The ndarray is NumPy's core object. All elements share one dtype, which is what makes it fast."),
    mc(Y, "NumPy", "What does np.array([1,2,3]) create?",
       "A one-dimensional ndarray containing 1, 2 and 3", ["A 3x3 array", "A Python tuple", "A pandas Series"],
       "np.array converts a Python list into an ndarray. A flat list gives a 1-D array."),
    mc(Y, "NumPy", "What does np.zeros(10) create?",
       "A 1-D array of ten values, each 0.0", ["A 10x10 array of zeros", "An array holding the numbers 0 through 10", "A single value, zero, repeated ten times as a list"],
       "The argument is the length. Values default to the float 0.0."),
    mc(Y, "NumPy", "What does np.arange(0,30,6) return?",
       "[0 6 12 18 24]", ["[0 6 12 18 24 30]", "[6 12 18 24 30]", "[0 5 10 15 20 25]"],
       "arange(start, stop, step) stops before the stop value, so 30 is excluded."),
    mc(Y, "NumPy", "What does np.random.random((2,2)) produce?",
       "A 2x2 array of random floats from 0.0 up to but not including 1.0",
       ["A 2x2 array of random integers from 0 to 2", "Two random integers", "A 1-D array with two random values"],
       "The shape is given as a tuple. random() generates floats in [0, 1)."),
    mc(Y, "NumPy", "What does the .shape attribute of an array return?",
       "A tuple giving the length of each dimension", ["The total number of elements", "The data type of the elements", "The number of dimensions only"],
       "For a 2-row, 3-column array, shape is (2, 3)."),
    mc(Y, "NumPy", "What does the .size attribute of an array return?",
       "The total number of elements in the array", ["A tuple of dimensions", "The memory used in bytes", "The number of rows"],
       "size is the product of the shape. A (2, 3) array has size 6."),
    mc(Y, "NumPy", "For an array created as np.array([[1,2,3],[4,5,6]]), what are shape and size?",
       "shape is (2, 3) and size is 6", ["shape is (3, 2) and size is 6", "shape is 6 and size is (2, 3)", "shape is (2, 3) and size is 5"],
       "Two rows, three columns gives (2, 3); 2 x 3 = 6 elements."),
    mt(Y, "NumPy", "Match each NumPy call to what it produces.",
       [("np.array([1,2,3])", "An array built from a list"),
        ("np.zeros(10)", "Ten values, each 0.0"),
        ("np.arange(0,30,6)", "Evenly spaced values that stop before 30"),
        ("np.random.random((2,2))", "A 2x2 array of random floats")],
       "Each function is a different way of creating an ndarray."),
    tf(Y, "NumPy", "In a NumPy ndarray, all elements must share the same data type.", Y,
       "That single dtype is why an ndarray is compact and fast compared with a mixed-type list."),
    tf(X, "NumPy", "array1.shape is a method, so you must write array1.shape() with parentheses.", X,
       "shape and size are attributes (stored values), written without parentheses."),
    mc(X, "NumPy", "What is the result of multiplying a NumPy array by 2, as in data * 2?",
       "Every element is doubled", ["The array is repeated twice, end to end", "Only the first element is doubled", "An error is raised"],
       "NumPy arithmetic is element-wise. With a Python list, data * 2 would repeat the list instead."),
    mc(X, "NumPy", "What is one advantage of an ndarray over a Python list for numeric work?",
       "It is faster and more memory-efficient and supports whole-array arithmetic", ["It can hold text and numbers mixed together", "It can grow automatically without limit", "It does not need to be imported"],
       "Homogeneous dtype and vectorized operations are the main benefits."),
    mc(X, "NumPy", "What does array1.ndim return for np.array([[1,2],[3,4]])?",
       "2", ["4", "(2, 2)", "1"],
       "ndim is the number of dimensions (axes). A table of rows and columns has 2."),
    mc(X, "NumPy", "What is the length of np.arange(0,30,6)?",
       "5", ["4", "6", "30"],
       "The values are 0, 6, 12, 18 and 24 - five elements."),
    mc(X, "NumPy", "What does np.zeros((3,4)) create?",
       "A 3x4 array filled with 0.0", ["A 1-D array of 34 zeros", "A 4x3 array filled with ones", "A list containing 3 and 4"],
       "Passing a tuple gives the shape: 3 rows and 4 columns."),
    mc(X, "NumPy", "What is the size of np.zeros((3,4))?",
       "12", ["7", "(3, 4)", "4"],
       "3 x 4 = 12 elements."),
    mc(X, "NumPy", "Which call is the correct way to create a 2x3 array of random floats?",
       "np.random.random((2,3))", ["np.random.random(2,3)", "np.random(2,3)", "np.array.random(2,3)"],
       "The shape must be passed as a single tuple, hence the double parentheses."),
    mc(X, "NumPy", "In np.arange(2, 20, 4), what does the 4 represent?",
       "The step between values", ["The number of values to create", "The stop value", "The starting value"],
       "The three arguments are start, stop, step. The result is [2 6 10 14 18]."),
    mc(X, "NumPy", "np.array([1, 2, 3]) has how many dimensions?",
       "1", ["2", "3", "0"],
       "A flat list produces a one-dimensional array; its shape is (3,)."),
    mc(X, "NumPy", "Why must the import statement come before the code that uses NumPy?",
       "Python does not know what np refers to until the library has been imported", ["The import statement sorts the code that follows", "Imports run only at the end of a program", "NumPy would otherwise run twice"],
       "Using np before import np raises a NameError."),
]))

# ================================================================ Calculations & Stats
SECTIONS.append(("Calculations & Statistics", [
    mc(Y, "Arithmetic", "NumPy arithmetic between two arrays of the same shape is applied how?",
       "Element by element (vectorized)", ["Only to the first row", "Once, to the array as a whole using a loop you must write", "Only after converting to lists"],
       "a + b adds matching positions. No explicit loop is needed."),
    mc(Y, "Aggregate", "What is an aggregate function?",
       "A function that reduces many values to a single summary value", ["A function that copies an array", "A function that sorts values", "A function that adds a new column"],
       "sum, mean, min, max and std are aggregates: many values in, one value out."),
    mc(Y, "Aggregate", "Which NumPy function returns the average of the values in an array?",
       "np.mean()", ["np.median()", "np.avg()", "np.average_sum()"],
       "NumPy and pandas use mean(). There is no avg() function."),
    mc(Y, "Aggregate", "For a 2-D array a, what does a.sum(axis=0) return?",
       "One total per column", ["One total per row", "A single grand total", "The array unchanged"],
       "axis=0 collapses down the rows, leaving one value for each column."),
    mc(Y, "Correlation", "What range of values can a correlation coefficient take?",
       "-1 to +1", ["0 to 1", "0 to 100", "-100 to +100"],
       "+1 is a perfect positive relationship, -1 a perfect negative one, 0 means no linear relationship."),
    mc(Y, "Correlation", "A correlation coefficient of -0.95 indicates what?",
       "A strong negative relationship: as one variable rises, the other tends to fall", ["A weak relationship", "That one variable causes the other to fall", "An error in the data"],
       "The sign gives direction, the size gives strength. Correlation never proves causation."),
    mc(Y, "Correlation", "Which function returns a correlation matrix for two NumPy arrays?",
       "np.corrcoef()", ["np.correlate_all()", "np.percentile()", "np.corrsum()"],
       "np.corrcoef(x, y) gives a 2x2 matrix whose off-diagonal entries are r."),
    mc(Y, "Percentiles", "What does the 90th percentile represent?",
       "The value at or below which 90% of the data falls", ["The value that is 90 times the mean", "The largest 90 values", "The value in position 90"],
       "A percentile marks a position in the sorted data as a percentage."),
    mc(X, "Percentiles", "What does np.percentile(data, 50) return?",
       "The median", ["The mean", "The maximum", "The value 50"],
       "The 50th percentile is the middle value of the sorted data."),
    mc(Y, "Percentiles", "Which values are the quartiles?",
       "The 25th, 50th and 75th percentiles", ["The 10th, 20th and 30th percentiles", "The min, mean and max", "The 1st, 2nd and 3rd values"],
       "Q1 = 25th, Q2 = median, Q3 = 75th percentile."),
    mt(Y, "Aggregate", "Match each function to what it returns.",
       [("np.sum()", "The total of all values"),
        ("np.mean()", "The average"),
        ("np.median()", "The middle value"),
        ("np.std()", "How spread out the values are")],
       "These are the common aggregate functions."),
    tf(Y, "Correlation", "A high correlation between two variables proves that one causes the other.", X,
       "Correlation only measures how closely they move together, not why."),
    tf(X, "Aggregate", "np.max(a) returns the largest value in the array.", Y, "max is an aggregate: many values in, one value out."),
    mc(X, "Percentiles", "How does np.percentile(a, 25) differ from np.quantile(a, 0.25)?",
       "They give the same result; percentile uses a 0-100 scale and quantile uses 0-1", ["quantile returns the mean instead", "percentile only works on 2-D arrays", "They give different results"],
       "Same statistic, different scale for the second argument."),
    mc(X, "Percentiles", "What is the interquartile range (IQR)?",
       "Q3 minus Q1, the spread of the middle 50% of the data", ["The maximum minus the minimum", "The mean minus the median", "Q1 plus Q3"],
       "IQR ignores the extremes, so outliers barely affect it."),
    mc(X, "Correlation", "In the matrix returned by np.corrcoef(x, y), what are the values on the diagonal?",
       "Always 1, because each variable correlates perfectly with itself", ["Always 0", "The means of x and y", "Always -1"],
       "The off-diagonal entries hold the correlation between x and y."),
    mc(X, "Correlation", "Which pandas call returns the correlation between every pair of numeric columns?",
       "df.corr()", ["df.correlate_all()", "df.count()", "df.cor_matrix"],
       "df.corr() returns a matrix of pairwise correlations."),
    mc(X, "Arithmetic", "If a = np.array([1,2,3]), what is a * 10?",
       "[10 20 30]", ["[1 2 3 10]", "[10 2 3]", "60"],
       "The single number is broadcast across every element."),
    mc(X, "Aggregate", "What does the standard deviation measure?",
       "How spread out the values are around the mean", ["The middle value", "The largest gap between neighbouring values", "The count of values"],
       "A small std means values cluster tightly around the mean."),
    mc(X, "Aggregate", "For a 2-D array a, what does a.sum(axis=1) return?",
       "One total per row", ["One total per column", "A single grand total", "A 1x1 array"],
       "axis=1 collapses across the columns, leaving one value for each row."),
]))

# ===================================================================== pandas basics
SECTIONS.append(("pandas: Series & DataFrames", [
    mc(Y, "Series", "What is a pandas Series?",
       "A one-dimensional labeled array of values", ["A two-dimensional table", "A sorted list of column names", "A file format for saving data"],
       "A Series is a single labeled column of data."),
    mc(Y, "DataFrame", "What is a pandas DataFrame?",
       "A two-dimensional labeled table of rows and columns", ["A one-dimensional array", "A NumPy function", "A plot type"],
       "Think of a spreadsheet or a SQL table."),
    mc(Y, "DataFrame", "What is the relationship between a DataFrame and a Series?",
       "Each column of a DataFrame is a Series", ["A DataFrame is a single Series", "A Series is a collection of DataFrames", "They are unrelated types"],
       "df['col'] returns a Series."),
    mc(Y, "Filtering", "What does df[df['field'] > 10] return?",
       "Only the rows where field is greater than 10", ["Every row, with non-matches set to NaN", "A single True or False", "The column named field"],
       "The inner expression creates a True/False mask; the outer brackets keep the True rows."),
    mc(Y, "Filtering", "How does df.where(df['field'] > 10) differ from df[df['field'] > 10]?",
       "where keeps the original shape and turns non-matching values into NaN; the subset drops the rows",
       ["where drops non-matching rows; the subset keeps them as NaN", "where only works on Series", "They return exactly the same thing"],
       "where preserves the shape of the data; boolean subsetting shrinks it."),
    mc(Y, "Filtering", "What does df.query('field > 10') do?",
       "Returns the rows matching a condition written as a string", ["Runs a SQL statement on a database", "Returns the column names containing 'field'", "Sorts the DataFrame by field"],
       "query() takes the condition as a string; column names go inside without quotes."),
    mc(Y, "Filtering", "Which call correctly selects rows where age is over 30 and city is Reno, using query()?",
       "df.query(\"age > 30 and city == 'Reno'\")", ["df.query(age > 30 & city = 'Reno')", "df.query(\"age > 30 && city = 'Reno'\")", "df.query([age > 30, city == 'Reno'])"],
       "Inside the query() string you can use and/or and == for comparison; string values need their own quotes."),
    mc(Y, "Filtering", "In the boolean-subset form, how do you combine two conditions with AND?",
       "df[(df['a'] > 1) & (df['b'] < 5)]", ["df[df['a'] > 1 and df['b'] < 5]", "df[df['a'] > 1, df['b'] < 5]", "df[(df['a'] > 1) + (df['b'] < 5)]"],
       "Use & with each condition in parentheses. Python's and does not work element-wise."),
    mc(Y, "Viewing", "What does df.head() return by default?",
       "The first 5 rows", ["The column names", "The first row only", "The last 5 rows"],
       "head(n) returns the first n rows; n defaults to 5."),
    mc(X, "Viewing", "What does df.tail(3) return?",
       "The last 3 rows", ["The first 3 rows", "Rows 3 onward", "The third row"],
       "tail(n) returns the last n rows."),
    mc(Y, "Counting", "Which call returns the number of rows for each unique value in the column 'city'?",
       "df['city'].value_counts()", ["df['city'].nunique()", "df['city'].unique()", "df['city'].count_all()"],
       "value_counts() gives a count per distinct value, most frequent first."),
    mc(Y, "Counting", "Which call returns the row count for each unique combination of two columns, 'a' and 'b'?",
       "df.groupby(['a','b']).size()", ["df['a'].nunique()", "df.unique(['a','b'])", "df.shape(['a','b'])"],
       "df[['a','b']].value_counts() also works. Both count rows per distinct pairing."),
    mc(Y, "Counting", "What does df['city'].nunique() return?",
       "A single number: how many different cities there are", ["A count for each city", "The list of city names", "The total number of rows"],
       "nunique = number of unique values."),
    mt(Y, "DataFrame", "Match each expression to its result.",
       [("df.head()", "The first 5 rows"),
        ("df.tail()", "The last 5 rows"),
        ("df.shape", "A tuple of (rows, columns)"),
        ("df['col'].value_counts()", "The number of rows for each unique value")],
       "These are the quickest ways to inspect a DataFrame."),
    tf(X, "Series", "A Series has both a set of values and an index of labels.", Y, "The index is what lets pandas align data by label."),
    tf(Y, "Filtering", "df.where() removes the rows that fail the condition.", X, "where keeps them, with NaN in place of the failing values."),
    tf(X, "Filtering", "Inside df.query(), you must put column names in quotes.", X, "Column names appear bare inside the string. Only string values need quotes."),
    mc(X, "Filtering", "What is the main syntactic difference between df[df['x'] > 10] and df.query('x > 10')?",
       "The first uses a Python boolean expression; the second uses a string expression", ["The first is for columns, the second for rows", "The second returns a Series", "The first cannot use comparison operators"],
       "Both give the same rows; only the way the condition is written differs."),
    mc(X, "Filtering", "What is the boolean mask df['x'] > 10 on its own?",
       "A Series of True/False values, one per row", ["A filtered DataFrame", "A single Boolean", "A list of column names"],
       "The mask is then used inside brackets to keep the True rows."),
    mc(X, "Viewing", "What does df.shape return for a DataFrame with 100 rows and 4 columns?",
       "(100, 4)", ["(4, 100)", "400", "104"],
       "shape gives (rows, columns)."),
    mc(X, "Viewing", "Which call shows each column's data type and count of non-null values?",
       "df.info()", ["df.head()", "df.shape", "df.describe()"],
       "describe() gives summary statistics; info() gives structure."),
    mc(X, "Counting", "What is the difference between unique() and nunique() on a column?",
       "unique() returns the distinct values; nunique() returns how many there are", ["unique() returns a count; nunique() returns the values", "They are aliases", "unique() works only on numbers"],
       "unique -> the values; nunique -> a number."),
    mc(X, "Counting", "How would you find how many rows are in a DataFrame?",
       "len(df)", ["df.unique()", "df.columns", "df.head()"],
       "df.shape[0] also gives the row count."),
    mc(X, "DataFrame", "Which code creates a DataFrame from a dictionary?",
       "pd.DataFrame({'a':[1,2],'b':[3,4]})", ["pd.Series({'a':[1,2],'b':[3,4]}, 2)", "np.dataframe({'a':[1,2]})", "pd.table('a','b')"],
       "Dictionary keys become column names and the lists become the columns."),
    mc(X, "Filtering", "You want to keep every row but blank out values that fail a condition. Which is best?",
       "df.where(condition)", ["df[condition]", "df.dropna()", "df.head(condition)"],
       "where preserves the shape and replaces failing values with NaN."),
    mc(X, "Series", "Which code creates a Series?",
       "pd.Series([10, 20, 30])", ["pd.DataFrame([10, 20, 30], [1])", "np.Series([10, 20, 30])", "pd.array2d([10, 20, 30])"],
       "pd.Series takes a list (or array) of values."),
]))

# ================================================================ Manipulating data
SECTIONS.append(("Manipulating Data", [
    mc(Y, "Reading data", "Which function reads a CSV file into a DataFrame?",
       "pd.read_csv()", ["pd.open_csv()", "np.read_csv()", "pd.load_table_csv_only()"],
       "read_csv returns a DataFrame; assign it to a variable."),
    mc(Y, "Reading data", "Which function reads a pickle (.pkl) file into a DataFrame?",
       "pd.read_pickle()", ["pd.read_pkl_text()", "pd.read_csv() with a .pkl name", "pd.open_pickle()"],
       "A pickle is Python's binary format that preserves dtypes and the index."),
    mc(Y, "Reading data", "What is a key difference between a CSV and a pickle file?",
       "A CSV is plain text; a pickle is a binary file that preserves data types exactly", ["A pickle is plain text; a CSV is binary", "A CSV can hold only numbers", "A pickle is readable in any text editor"],
       "The CSV is portable and human-readable; the pickle is Python-specific."),
    mc(Y, "Columns", "Which statement adds a new column named 'total' that is the sum of columns 'a' and 'b'?",
       "df['total'] = df['a'] + df['b']", ["df.add_column('total', a + b)", "df.total(a + b)", "df.insert('total')"],
       "Assigning to a new column name creates it."),
    mc(Y, "Columns", "Which call renames column 'old' to 'new'?",
       "df.rename(columns={'old': 'new'})", ["df.rename('old', 'new')", "df.columns.change('old' -> 'new')", "df.rename({'new': 'old'})"],
       "rename takes a dictionary of old name -> new name."),
    mc(Y, "Columns", "Which call removes the columns 'a' and 'b'?",
       "df.drop(columns=['a', 'b'])", ["df.remove(['a', 'b'])", "df.dropna(columns=['a', 'b'])", "df.delete('a', 'b')"],
       "drop(columns=[...]) or drop([...], axis=1). dropna removes missing values, not columns by name."),
    mc(X, "Columns", "In df.drop(['a'], axis=1), what does axis=1 mean?",
       "Operate on columns", ["Operate on rows", "Operate on the index only", "Drop the first item only"],
       "axis=0 is rows (the default), axis=1 is columns."),
    mc(Y, "Combining", "Which function combines two DataFrames by matching values in a shared key column?",
       "pd.merge()", ["pd.concat()", "pd.append_rows()", "pd.stack()"],
       "merge is pandas' join, like a SQL JOIN."),
    mc(Y, "Combining", "Which function appends the rows of one DataFrame beneath another with the same columns?",
       "pd.concat([df1, df2])", ["pd.merge(df1, df2)", "pd.join(df1)", "pd.pivot(df1, df2)"],
       "concat stacks along axis=0 (rows) by default."),
    mc(Y, "Combining", "Which best describes what merge() does to the width of the data?",
       "It brings in new columns by matching rows on a key", ["It adds new rows only", "It removes duplicate columns", "It converts wide data to long"],
       "merge adds columns from a second table, matched on a key."),
    mc(Y, "Combining", "What is the default join type used by pd.merge()?",
       "Inner - only keys found in both tables", ["Outer - all keys from both tables", "Left - all rows from the first table", "Right - all rows from the second table"],
       "Use how='left', 'right' or 'outer' to change it."),
    mt(Y, "Combining", "Match each pandas function to its purpose.",
       [("pd.merge()", "Add columns by matching a key"),
        ("pd.concat()", "Stack data sets together"),
        ("pd.read_csv()", "Load a text data file"),
        ("df.rename()", "Change column names")],
       "Together these cover loading, reshaping and combining data."),
    tf(Y, "Combining", "pd.concat() requires a shared key column, like merge().", X,
       "concat stacks by position and labels; it does not match on a key."),
    tf(X, "Columns", "df.rename(columns={'old':'new'}) changes df in place unless you reassign or use inplace=True.", X,
       "It returns a new DataFrame; the original is unchanged unless you reassign or set inplace=True."),
    tf(X, "Reading data", "pd.read_csv() returns a DataFrame.", Y, "Assign it: df = pd.read_csv('file.csv')."),
    mc(X, "Combining", "What does pd.concat([df1, df2], axis=1) do?",
       "Places the DataFrames side by side, adding columns", ["Stacks df2 beneath df1", "Merges on the index and key", "Removes duplicates"],
       "axis=1 joins along columns; axis=0 (default) joins along rows."),
    mc(X, "Combining", "What is a potential side effect of concat() on the index?",
       "The original index labels are kept, so duplicate labels can appear", ["The index is deleted", "All indexes become strings", "The index is sorted automatically"],
       "Use ignore_index=True to renumber 0..n-1."),
    mc(X, "Combining", "Which merge type keeps all rows from both tables, filling gaps with NaN?",
       "how='outer'", ["how='inner'", "how='left'", "how='common'"],
       "outer = everything from both sides."),
    mc(X, "Combining", "Which merge type keeps every row of the left table plus matches from the right?",
       "how='left'", ["how='right'", "how='inner'", "how='all'"],
       "Left join: the left table is preserved in full."),
    mc(X, "Columns", "Which statement gives every row of a new column 'flag' the value 1?",
       "df['flag'] = 1", ["df.flag == 1", "df.add('flag')", "df['flag'] == 1"],
       "Assigning a single value fills the whole column."),
    mc(X, "Columns", "What does df.drop(index=[0, 1]) remove?",
       "The rows with index labels 0 and 1", ["Columns 0 and 1", "The first two duplicates", "All rows except 0 and 1"],
       "drop by index removes rows; drop by columns removes columns."),
    mc(X, "Reading data", "Why might you choose a pickle over a CSV to save a DataFrame?",
       "It preserves data types and the index exactly", ["It can be opened in a text editor", "It works in other languages by default", "It is always smaller"],
       "CSV must re-infer types on load; pickle stores them."),
    mc(X, "Combining", "To add the columns of a second table to the first by matching on 'id', which call is appropriate?",
       "pd.merge(a, b, on='id')", ["pd.concat([a, b], on='id')", "a.drop(b)", "pd.pivot(a, b)"],
       "on= names the key column that both tables share."),
    mc(X, "Combining", "Two DataFrames have the same columns and you want to add the second one's rows to the first. Which is correct?",
       "pd.concat([df1, df2])", ["pd.merge(df1, df2, on='id')", "df1.rename(df2)", "df1.stack(df2)"],
       "Same columns and types - append rows with concat."),
]))

# ================================================================== Indexes
SECTIONS.append(("Indexes", [
    mc(Y, "Index", "What is the default index of a newly created DataFrame?",
       "A RangeIndex: integers 0, 1, 2, ... n-1", ["An alphabetical list of column names", "No index at all", "The values of the first column"],
       "RangeIndex is assigned automatically when you do not specify one."),
    mc(Y, "Index", "What is a multi-index?",
       "A hierarchical index with two or more levels", ["An index containing duplicate labels", "Two DataFrames sharing an index", "A column of repeated values"],
       "For example, (country, year) as the row label."),
    mc(Y, "Index", "What does df.set_index('id') do?",
       "Makes the 'id' column the index of the DataFrame", ["Adds an id column", "Sorts the data by id", "Deletes the index"],
       "set_index moves a column into the index."),
    mc(Y, "Index", "What does df.reset_index() do?",
       "Moves the index back into a column and installs a new 0..n-1 RangeIndex", ["Deletes all rows", "Sorts the index", "Converts the index to a Series"],
       "It is the inverse of set_index."),
    mc(X, "Index", "What does df.reset_index(drop=True) do differently?",
       "It creates a fresh RangeIndex and discards the old index instead of keeping it as a column", ["It removes all columns", "It drops duplicate rows", "It leaves the index unchanged"],
       "Useful after filtering when the old labels are not needed."),
    mc(Y, "Index", "How do you create a multi-index from the columns 'country' and 'year'?",
       "df.set_index(['country', 'year'])", ["df.multi_index('country', 'year')", "df.reset_index(['country', 'year'])", "df.index = 'country' + 'year'"],
       "Pass a list to set_index."),
    mt(Y, "Index", "Match each term to its meaning.",
       [("RangeIndex", "The default 0..n-1 integer index"),
        ("MultiIndex", "An index with more than one level"),
        ("set_index()", "Turn a column into the index"),
        ("reset_index()", "Turn the index back into a column")],
       "These four terms cover everything the exam asks about indexes."),
    tf(Y, "Index", "After df.dropna(), the remaining rows keep their original index labels.", Y,
       "Use reset_index(drop=True) if you want them renumbered."),
    tf(X, "Index", "set_index() and reset_index() are inverse operations.", Y, "One moves a column to the index; the other moves it back."),
    mc(X, "Index", "After filtering rows with df[df['x'] > 10], the index is:",
       "Unchanged - the surviving rows keep their original labels", ["Renumbered from 0 automatically", "Deleted", "Converted to a multi-index"],
       "The labels can therefore have gaps. reset_index(drop=True) closes them."),
    mc(X, "Index", "Why is reset_index() commonly used after groupby()?",
       "groupby puts the group keys in the index; reset_index turns them back into ordinary columns", ["To sort the groups", "To remove null groups", "To convert the result to a Series"],
       "Alternatively use as_index=False in groupby."),
    mc(X, "Index", "Which statement about a RangeIndex is true?",
       "It is generated automatically and counts up from 0", ["It must be typed in manually", "It always holds text labels", "It is created only by set_index"],
       "It is what you get by default."),
    mc(X, "Index", "What is a typical reason to use set_index()?",
       "To look up rows by a meaningful label such as an ID", ["To add a new row", "To convert strings to numbers", "To delete duplicate columns"],
       "Labels make rows addressable by name rather than position."),
    mc(X, "Index", "What is the effect of reset_index() on a multi-index?",
       "The index levels become regular columns and a RangeIndex is restored", ["It creates a deeper multi-index", "It deletes the levels", "It sorts the levels"],
       "It flattens the hierarchy."),
]))

# ============================================================= Cleaning & imputation
SECTIONS.append(("Data Cleaning & Imputation", [
    mc(Y, "Duplicates", "Which method removes duplicate rows from a DataFrame?",
       "df.drop_duplicates()", ["df.dropna()", "df.remove_dupes()", "df.unique_rows()"],
       "By default it keeps the first copy of each duplicated row."),
    mc(Y, "Duplicates", "By default, which copy does drop_duplicates() keep?",
       "The first occurrence", ["The last occurrence", "None of them", "The one with the smallest index"],
       "keep='first' is the default; keep='last' keeps the final copy."),
    mc(Y, "Missing data", "Which method returns True for each missing value in a DataFrame?",
       "df.isnull()", ["df.notnull()", "df.dropna()", "df.missing()"],
       "isna() does the same. notnull() is the opposite."),
    mc(Y, "Missing data", "How do you count the missing values in each column?",
       "df.isnull().sum()", ["df.isnull().count_all", "df.sum().isnull()", "df.nulls()"],
       "True counts as 1, so sum() counts the missing values per column."),
    mc(Y, "Missing data", "What does df.dropna() do by default?",
       "Removes every row that contains at least one missing value", ["Removes only rows where every value is missing", "Removes columns with missing values", "Fills missing values with zero"],
       "The default is how='any', axis=0."),
    mc(X, "Missing data", "What does df.dropna(how='all') do?",
       "Removes only rows in which every value is missing", ["Removes every row with any missing value", "Removes all columns", "Removes all rows"],
       "how='all' is much more conservative than the default 'any'."),
    mc(Y, "Imputation", "What is imputation?",
       "Replacing missing values with substituted values", ["Deleting rows that contain missing values", "Finding duplicate rows", "Converting text to numbers"],
       "Imputation keeps the row by filling the gap instead of dropping it."),
    mc(Y, "Imputation", "Which method replaces every missing value in a DataFrame with 0?",
       "df.fillna(0)", ["df.dropna(0)", "df.replace_missing(0)", "df.isnull(0)"],
       "fillna(value) fills NaN with the given value."),
    mc(Y, "Imputation", "What does forward-fill (ffill) do?",
       "Copies the last valid value down into the missing positions that follow it", ["Copies the next valid value up into the gap", "Fills gaps with the column average", "Deletes the gap"],
       "Forward = carry the previous value forward."),
    mc(Y, "Imputation", "What does backfill (bfill) do?",
       "Fills a gap with the next valid value that appears after it", ["Fills a gap with the previous valid value", "Fills a gap with 0", "Removes the row"],
       "Backward = pull the following value back up."),
    mc(Y, "Imputation", "Which code performs a mean-fill on the column 'score'?",
       "df['score'].fillna(df['score'].mean())", ["df['score'].dropna(df['score'].mean())", "df['score'].mean(fillna)", "df['score'].fill(mean)"],
       "Compute the mean (ignoring NaN), then use it as the fill value."),
    mt(Y, "Cleaning", "Match each method to what it does.",
       [("drop_duplicates()", "Removes repeated rows"),
        ("isnull()", "Flags missing values"),
        ("dropna()", "Removes rows with missing values"),
        ("fillna()", "Replaces missing values")],
       "Detect with isnull, remove with dropna, replace with fillna."),
    tf(Y, "Missing data", "df.isnull() and df.isna() give the same result.", Y, "They are aliases."),
    tf(X, "Imputation", "Mean-fill computes the average using the missing values as zeros.", X,
       "The mean ignores NaN by default."),
    tf(X, "Missing data", "dropna() changes the number of rows, but fillna() does not.", Y, "fillna keeps every row; dropna deletes some."),
    mc(X, "Duplicates", "Which call identifies duplicate rows without removing them?",
       "df.duplicated()", ["df.drop_duplicates()", "df.isnull()", "df.unique()"],
       "duplicated() returns a True/False Series marking repeats."),
    mc(X, "Duplicates", "How do you drop duplicates judged only on the column 'email'?",
       "df.drop_duplicates(subset=['email'])", ["df.drop_duplicates('email', all)", "df.dropna(subset=['email'])", "df.unique(['email'])"],
       "subset restricts the comparison to the named columns."),
    mc(X, "Missing data", "Which method returns True for values that are NOT missing?",
       "df.notnull()", ["df.isnull()", "df.dropna()", "df.exists()"],
       "notnull() is the opposite of isnull()."),
    mc(X, "Missing data", "How would you drop only rows where 'price' is missing?",
       "df.dropna(subset=['price'])", ["df.dropna(how='all')", "df.drop('price')", "df.fillna(subset=['price'])"],
       "subset limits the check to the named column(s)."),
    mc(X, "Imputation", "Which is a reason to impute rather than drop rows with missing data?",
       "It preserves the sample size", ["It always improves accuracy", "It removes bad data", "It is required before any plot"],
       "Dropping can shrink the data set and bias results."),
    mc(X, "Imputation", "A column has values 5, NaN, NaN, 9. After ffill, the column is:",
       "5, 5, 5, 9", ["5, 9, 9, 9", "5, 7, 7, 9", "5, 0, 0, 9"],
       "Each gap copies the last valid value above it."),
    mc(X, "Imputation", "A column has values 5, NaN, NaN, 9. After bfill, the column is:",
       "5, 9, 9, 9", ["5, 5, 5, 9", "5, 7, 7, 9", "9, 9, 9, 9"],
       "Each gap copies the next valid value below it."),
    mc(X, "Imputation", "Why might you fill with the median instead of the mean?",
       "The median is less affected by extreme values", ["The median is always larger", "The mean cannot handle NaN", "The median works only on text"],
       "Outliers pull the mean but hardly move the median."),
]))

# ============================================================================ Analysis
SECTIONS.append(("Analysis: Reshaping & Grouping", [
    mc(Y, "Reshaping", "What does stack() do?",
       "Moves column labels into the row index, making the data longer", ["Moves index levels out into columns", "Adds rows from another table", "Removes duplicate rows"],
       "stack: wide to long."),
    mc(Y, "Reshaping", "What does unstack() do?",
       "Moves an index level out into columns, making the data wider", ["Moves columns into the index", "Sorts the index", "Deletes the index"],
       "unstack is the inverse of stack: long to wide."),
    mc(X, "Reshaping", "Which statement best compares stack and unstack?",
       "They are inverse operations that reshape between long and wide formats", ["Both remove missing values", "stack works only on Series", "They are aliases"],
       "One lengthens, the other widens."),
    mc(Y, "Reshaping", "What is the key difference between pivot() and pivot_table()?",
       "pivot_table() aggregates duplicate entries; pivot() only reshapes and errors on duplicates", ["pivot() aggregates; pivot_table() does not", "pivot_table() only works on Series", "There is no difference"],
       "pivot needs each index/column pair to be unique."),
    mc(Y, "Reshaping", "What is the default aggregation function of pivot_table()?",
       "mean", ["sum", "count", "max"],
       "Use aggfunc='sum' etc. to change it."),
    mc(Y, "Reshaping", "In df.pivot(index='month', columns='product', values='sales'), what supplies the column headings?",
       "The distinct values of 'product'", ["The distinct values of 'month'", "The 'sales' column", "The column names of the original DataFrame"],
       "index -> row labels; columns -> new headings; values -> cell contents."),
    mc(Y, "Grouping", "What does groupby() do?",
       "Splits rows into groups by a key, applies a function to each group and combines the results", ["Sorts the DataFrame alphabetically", "Removes duplicate groups", "Merges two DataFrames"],
       "It is the split-apply-combine pattern."),
    mc(Y, "Grouping", "Which code gives the average salary for each department?",
       "df.groupby('dept')['salary'].mean()", ["df.mean('dept', 'salary')", "df['salary'].groupby.avg('dept')", "df.groupby('salary')['dept'].mean()"],
       "Group by the category, select the column, then aggregate."),
    mc(Y, "Grouping", "Which aggregate function name is NOT valid in pandas?",
       "avg()", ["sum()", "mean()", "max()"],
       "The average is mean(). avg() is the SQL name."),
    mc(Y, "Grouping", "What does the aggregate function agg() (or aggregate()) let you do?",
       "Apply one or several aggregate functions at once, even a different one per column", ["Append rows", "Change the index", "Rename columns"],
       "e.g., df.groupby('dept').agg({'salary':['min','max'], 'age':'mean'})"),
    mt(Y, "Grouping", "Match each aggregate function to its result within each group.",
       [("sum()", "The total"),
        ("mean()", "The average"),
        ("min()", "The smallest value"),
        ("max()", "The largest value")],
       "These are the basic groupby aggregates."),
    tf(Y, "Reshaping", "pivot() will raise an error if an index/column pair appears more than once.", Y,
       "That is exactly the situation pivot_table() was designed to handle."),
    tf(X, "Grouping", "After groupby(), the group keys become the index of the result.", Y, "reset_index() or as_index=False turns them back into columns."),
    tf(X, "Reshaping", "stack() makes a DataFrame wider.", X, "stack makes it longer (narrower). unstack widens."),
    mc(X, "Grouping", "What is the difference between count() and size() in a groupby?",
       "count() counts non-null values; size() counts all rows including nulls", ["size() counts non-null only; count() counts all rows", "They are identical", "count() sums values"],
       "The gap appears when a column has missing values."),
    mc(X, "Grouping", "Which is the correct order of steps in groupby?",
       "Split, apply, combine", ["Apply, split, combine", "Combine, split, apply", "Sort, filter, plot"],
       "Split into groups, apply a function, combine the results."),
    mc(X, "Reshaping", "Which call totals sales for each month/product pair in a wide grid?",
       "df.pivot_table(index='month', columns='product', values='sales', aggfunc='sum')", ["df.pivot(index='month', columns='product', values='sales', aggfunc='sum')", "df.groupby('sales').pivot()", "df.stack('month', 'product')"],
       "pivot() does not take an aggfunc; pivot_table() does."),
    mc(X, "Grouping", "Which call finds the highest salary in each department?",
       "df.groupby('dept')['salary'].max()", ["df['salary'].max('dept')", "df.max(groupby='dept')", "df.groupby('salary').max('dept')"],
       "Group, select the column, aggregate."),
    mc(X, "Reshaping", "Long format usually means:",
       "Few columns and many rows, with one observation per row", ["Many columns and few rows", "A DataFrame with no index", "Data stored in a pickle"],
       "stack produces long format; unstack/pivot produce wide."),
    mc(X, "Grouping", "What does as_index=False do in groupby?",
       "Keeps the group keys as ordinary columns instead of putting them in the index", ["Removes the group keys", "Sorts the result", "Turns off aggregation"],
       "It has the same effect as calling reset_index() afterwards."),
]))

# ========================================================================= Visualization
SECTIONS.append(("Visualization", [
    mc(Y, "Plotting", "Which statement displays the current plot in a script?",
       "plt.show()", ["plt.display()", "plt.print()", "df.show_plot"],
       "matplotlib's show() draws the figure window."),
    mc(Y, "Plotting", "Which import provides the plt alias used for plotting?",
       "import matplotlib.pyplot as plt", ["import plot as plt", "import numpy.plot as plt", "import pandas.plt"],
       "plt is the standard alias for matplotlib.pyplot."),
    mc(Y, "Plotting", "What does calling df.plot() with no arguments produce?",
       "A line plot of the numeric columns against the index", ["A histogram", "A boxplot", "A table"],
       "Line is the default kind."),
    mc(Y, "Histogram", "What does a histogram show?",
       "The distribution of one numeric variable, grouped into bins", ["The relationship between two variables", "The median and outliers only", "Values for each category"],
       "Bar height is the count of values in each bin."),
    mc(Y, "Histogram", "In a histogram, which argument controls how many bars are drawn?",
       "bins", ["width", "rows", "count"],
       "e.g., df['col'].hist(bins=20)."),
    mc(Y, "Scatter", "What does a scatter plot show?",
       "The relationship between two numeric variables, one point per row", ["The distribution of one variable", "The five-number summary", "Counts by category"],
       "Use it to see whether two variables are correlated."),
    mc(Y, "Scatter", "Which call draws a scatter plot from two columns of a DataFrame?",
       "df.plot.scatter(x='a', y='b')", ["df.plot.scatter('a')", "df.hist(x='a', y='b')", "df.boxplot(x='a', y='b')"],
       "It needs both an x and a y column."),
    mc(Y, "Scatter", "How do you make a scatter plot with a line connecting the points?",
       "Plot with markers and a line, for example plt.plot(x, y, 'o-')", ["Call plt.hist(x, y)", "Call plt.boxplot(x, y)", "It is impossible in matplotlib"],
       "Or call plt.scatter() and plt.plot() on the same axes."),
    mc(Y, "Boxplot", "What does a boxplot (box-and-whisker plot) summarize?",
       "The median, quartiles, spread and outliers of a variable", ["The relationship between two variables", "Only the mean", "Counts of each category"],
       "It is a graphical five-number summary."),
    mc(X, "Boxplot", "In a boxplot, what does the line inside the box represent?",
       "The median", ["The mean", "The maximum", "The mode"],
       "The box edges are Q1 and Q3."),
    mc(Y, "Boxplot", "In a boxplot, what do the individual dots beyond the whiskers represent?",
       "Outliers", ["The mean", "Missing values", "Duplicate rows"],
       "They are values further than about 1.5 x IQR from the box."),
    mt(Y, "Plotting", "Match each plot type to what it is best for.",
       [("Histogram", "Distribution of one numeric variable"),
        ("Scatter plot", "Relationship between two numeric variables"),
        ("Boxplot", "Median, spread and outliers"),
        ("Line plot", "Trend over an ordered axis such as time")],
       "Choosing the right plot starts with what you want to show."),
    tf(X, "Plotting", "pandas' df.plot() draws using matplotlib.", Y, "pandas plotting is a convenient wrapper around matplotlib."),
    tf(Y, "Histogram", "A histogram compares values across categories.", X, "That is a bar chart. A histogram shows a numeric distribution."),
    tf(X, "Boxplot", "The box in a boxplot spans from Q1 to Q3.", Y, "The box height is the interquartile range."),
    mc(X, "Plotting", "Which call adds a title to a matplotlib plot?",
       "plt.title('My Title')", ["plt.header('My Title')", "plt.name('My Title')", "plt.text_title = 'My Title'"],
       "Also plt.xlabel() and plt.ylabel() for the axis labels."),
    mc(X, "Histogram", "Which call draws a histogram of one DataFrame column?",
       "df['col'].hist()", ["df['col'].scatter()", "df['col'].boxplot_hist", "df.plot.hist('col', 'col')"],
       "df['col'].plot(kind='hist') is equivalent."),
    mc(X, "Boxplot", "Which call draws a boxplot of the numeric columns in a DataFrame?",
       "df.boxplot()", ["df.box_hist()", "df.scatter_box()", "df.plot.box_only"],
       "df.plot(kind='box') also works."),
    mc(X, "Scatter", "Which plot is the best first check before relying on a correlation coefficient?",
       "A scatter plot", ["A histogram", "A boxplot", "A pie chart"],
       "It shows whether the relationship is roughly linear or driven by outliers."),
    mc(X, "Histogram", "How does a histogram differ from a bar chart?",
       "A histogram bins a continuous numeric variable; a bar chart compares distinct categories", ["A histogram is for text; a bar chart is for numbers", "They are identical", "A histogram has no y-axis"],
       "Histogram bars represent numeric ranges."),
    mc(X, "Boxplot", "What is the IQR shown by in a boxplot?",
       "The height of the box", ["The length of the whiskers", "The dots", "The line in the box"],
       "IQR = Q3 - Q1, the middle 50% of the data."),
]))
