"""Comprehensive additions to the ITD 145 final exam review.

The final is comprehensive, so these questions cover the course's statistics and
pandas topics beyond the original study-guide outline: importing and inspecting data,
cleaning, reshaping, descriptive statistics, distributions and hypothesis testing. They are
original questions, with their own scenarios, numbers and wording.

Called at the bottom of itd145_final_questions.py as extend(SECTIONS, helpers...).
"""


def extend(SECTIONS, mc, tf, fb, mt, sa, EMP):
    by = {name.split(". ", 1)[1]: qs for name, qs in SECTIONS}

    # ------------------------------------------------------------------ statistics
    c = "Descriptive Statistics"
    by["Descriptive Statistics"].extend([
        mc(c, "What is the MODE of this sample: [2, 3, 3, 5, 7, 7, 7, 9, 12, 12]?",
           "7", ["3", "12", "5"],
           "The mode is the value that occurs most often. 7 appears three times, more than any other value."),
        mc(c, "What is the MEDIAN of this unsorted sample: [9, 1, 7, 3, 5]?",
           "5", ["7", "3", "9"],
           "Sort first: 1, 3, 5, 7, 9. The middle value is 5. Taking the middle of the list as given would give 7."),
        mc(c, "What is the MEAN of this sample: [4, 8, 15, 16, 23, 42]?",
           "18", ["15.5", "16", "20"],
           "The sum is 108 and there are 6 values, so the mean is 108 / 6 = 18. The median is 15.5."),
        mc(c, "Which pair contains only measures of spread?",
           "standard deviation and interquartile range",
           ["mean and standard deviation", "median and interquartile range", "mode and variance"],
           "Mean, median and mode describe the center; standard deviation, variance, range and IQR describe how spread out the data are."),
        mc(c, "A data set of home prices has a mean of $420,000 and a median of $350,000. What does this suggest?",
           "The distribution is probably right-skewed, with a few very expensive homes",
           ["The distribution is probably left-skewed, with a few very cheap homes",
            "The distribution is probably symmetric, with the prices evenly spread",
            "The distribution is probably uniform, with each price equally likely"],
           "The mean sits above the median when a few large values pull it up, which is positive (right) skew."),
        mc(c, "In a right-skewed distribution, which measure of center sits farthest out toward the long tail?",
           "the mean", ["the median", "the mode", "the midrange"],
           "The mean is the most sensitive to extreme values, so it is dragged farthest toward the tail; the mode stays near the peak."),
        mc(c, "A salary column includes one executive paid 100 times as much as everyone else. Which call best summarizes a typical salary?",
           "df['salary'].median()",
           ["df['salary'].mean()", "df['salary'].max()", "df['salary'].sum()"],
           "The mean would be dragged upward by the executive's pay; the median depends only on the middle of the sorted values."),
        mc(c, "Two normal curves have the same mean. Curve A has a standard deviation of 2 and curve B has a standard deviation of 6. How do they compare?",
           "Curve B is wider and has a lower peak than curve A",
           ["Curve B is wider and has a higher peak than curve A", "Curve B is narrower and has a higher peak than curve A", "The curves have the same shape, since their means match"],
           "The total area stays 1, so spreading the values out lowers the peak."),
        mc(c, "Maria scored 82 on an exam with a mean of 70 and a standard deviation of 6. Jon scored 75 on a different exam with a mean of 60 and a standard deviation of 10. Who did relatively better, compared with their own exam?",
           "Maria, because her z-score of 2 is higher than Jon's z-score of 1.5",
           ["Jon, because his score is 15 points above his mean and Maria's is only 12 above hers",
            "They did equally well, because both of the scores are above the mean of their exam",
            "Maria, because 82 is a larger number than 75 and the exams can be compared directly"],
           "Z-scores put different scales on a common footing: Maria (82 − 70) / 6 = 2.0; Jon (75 − 60) / 10 = 1.5."),
    ])

    c = "Random Variables & Distributions"
    by["Random Variables and Distributions"].extend([
        tf(c, "The number of coin flips needed to get the first head is a discrete random variable, even though there is no maximum number of flips.", True,
           "The possible values 1, 2, 3, ... can be counted one by one, so the variable is discrete even though the list never ends."),
        tf(c, "If a random variable has infinitely many possible values, it must be a continuous random variable.", False,
           "Discrete means countable. A count with no upper limit has infinitely many values but is still discrete."),
        tf(c, "Between any two possible values of a continuous random variable, there are more possible values.", True,
           "Between 170.1 cm and 170.2 cm lie 170.15 cm, 170.11 cm and so on without end, which is why exact values have probability zero."),
        mc(c, "Which of these fully describes a random variable?",
           "its probability distribution: the possible values and how likely each one is",
           ["its mean, which summarizes the typical value of the variable", "its range, from the smallest to the largest possible value", "its sample size, which is the number of times it was observed"],
           "The mean and range are summaries. The distribution describes the whole behavior of the variable."),
        mc(c, "A discrete random variable takes the values 0, 1 and 2 with probabilities 0.2, 0.5 and 0.3. What is its expected value?",
           "1.1", ["1.0", "0.5", "2.0"],
           "Expected value = Σ x·p = 0(0.2) + 1(0.5) + 2(0.3) = 1.1. It is the probability-weighted average, not necessarily a possible outcome."),
        mc(c, "If you repeat a random experiment thousands of times, the average of the outcomes settles near the random variable's ___.",
           "expected value", ["mode", "range", "sample size"],
           "The expected value is the long-run mean, the probability-weighted average of the outcomes. For a fair die it is 3.5."),
        mc(c, "Of 12 randomly chosen customers, each either clicks an ad or does not, with the same chance every time. The number who click follows which distribution?",
           "binomial", ["Poisson", "uniform", "normal"],
           "A fixed number of independent yes-or-no trials with the same probability of success is the binomial setting."),
        mc(c, "The number of typos on a page is modeled with a Poisson distribution. Which statement about this variable is true?",
           "It is discrete, because it counts events and takes whole-number values",
           ["It is continuous, because a page could have any number of typos at all",
            "It is continuous, because the Poisson is just a type of normal distribution",
            "It is neither discrete nor continuous, because the number of typos is random"],
           "Counts are discrete. Poisson is not a variation of the normal curve; it models the number of events in a fixed interval."),
        mc(c, "A lottery machine draws a number from 1 to 49, each equally likely. After 100,000 draws, a bar chart of how often each number came up would look ___.",
           "roughly flat", ["bell-shaped", "right-skewed", "two-peaked"],
           "Equal probabilities give equal long-run frequencies, a uniform distribution."),
        tf(c, "In a normal, non-skewed distribution, the mean, median and mode are all equal.", True,
           "The symmetric bell shape puts all three at the center."),
    ])

    c = "Inferential Statistics"
    by["Inferential Statistics"].extend([
        mc(c, "Why do statisticians often like to have samples of at least about 30?",
           "Because the sample mean's behavior is then reasonably close to a normal curve",
           ["Because 30 is the legal minimum for publishing the results of a survey",
            "Because a sample smaller than 30 cannot be used to calculate a standard deviation",
            "Because with 30 values the sample mean becomes exactly equal to the population mean"],
           "This is the central-limit idea. About 30 is a rule of thumb, and skewed populations need more."),
        mc(c, "What does it mean to call a result 'statistically significant'?",
           "A result like this would be unlikely to happen by chance alone if the null hypothesis were true",
           ["The result is large enough to matter in practice for the people it affects",
            "The result has been confirmed by a second, independent study of the same question",
            "The null hypothesis has been proven false with complete certainty by the test"],
           "Significance is about chance, set by α. It says nothing about the size or importance of the effect."),
        mc(c, "A test is run at α = 0.05. Which of these results would NOT be called statistically significant?",
           "p = 0.07", ["p = 0.03", "p = 0.001", "p = 0.049"],
           "A result is significant only when p < α. 0.07 is above 0.05, so the null is not rejected."),
        mc(c, "A researcher lowers the significance level from α = 0.05 to α = 0.01. What happens to the chance of a Type I error?",
           "It decreases, because the test now demands stronger evidence before rejecting the null",
           ["It increases, because fewer results can now be called statistically significant",
            "It is unchanged, because α only affects how often a Type II error happens",
            "It drops to zero, because a stricter test can never reject a true null"],
           "α is the Type I error rate. Lowering it makes false positives rarer, at the cost of more Type II errors."),
        mc(c, "Why do analysts report a confidence interval alongside a sample mean, instead of the sample mean alone?",
           "Because the interval shows how precise the estimate is, which a single number cannot",
           ["Because the interval replaces the sample mean once the sample is large enough",
            "Because the interval proves that the null hypothesis has been rejected by the data",
            "Because the interval lists every individual value that was found in the sample"],
           "A mean of 52 could be 52 ± 1 or 52 ± 20. The interval's width communicates the uncertainty."),
    ])

    c = "Outliers & Choosing a Plot"
    by["Outliers and Choosing a Plot"].extend([
        mc(c, "Why is the IQR a more robust measure of spread than the range when one value in the data is extreme?",
           "It uses only the middle half of the data, so a single extreme value barely changes it",
           ["It uses every value in the data equally, so an extreme value is averaged away",
            "It is measured in squared units, which makes one extreme value matter less",
            "It is recalculated after the most extreme value has been deleted by hand"],
           "The range depends entirely on the two most extreme values. The IQR (Q3 − Q1) ignores the outer quarter on each side."),
        mc(c, "A box-whisker plot has a long upper whisker, and its median line sits close to the bottom of the box. What does this suggest about the data?",
           "The data are right-skewed, with the upper half more spread out than the lower half",
           ["The data are left-skewed, with the lower half more spread out than the upper half",
            "The data are symmetric, with both halves spread out by the same amount",
            "The data contain no values at all above the third quartile of the data"],
           "A median near Q1 plus a long upper whisker means the top half of the values stretches much farther than the bottom half."),
        mc(c, "A study of 500 students finds r = 0.05 between shoe size and exam score. Which conclusion is best?",
           "There is no meaningful linear relationship between shoe size and exam score",
           ["Larger shoe size causes slightly higher exam scores among the students",
            "Shoe size predicts exam score with a high degree of accuracy for students",
            "Shoe size and exam score are strongly related, but the sign is unreliable"],
           "An r this close to 0 says a straight-line trend is negligible. Even a large r would not prove causation."),
    ])

    # ------------------------------------------------------------------ importing & inspecting
    c = "Python, Importing & Inspecting Data"
    imp = [
        mc(c, "Which line creates a dictionary that maps 'M' to 'Male' and 'F' to 'Female'?",
           "{'M': 'Male', 'F': 'Female'}",
           ["['M': 'Male', 'F': 'Female']", "('M': 'Male', 'F': 'Female')", "{'M', 'Male', 'F', 'Female'}"],
           "A dictionary uses curly braces with key: value pairs. The last option is a set of four items, not a mapping."),
        mc(c, "What does df['sex'].map({'M': 'Male', 'F': 'Female'}) do?",
           "returns a new Series in which each M is replaced by Male and each F by Female",
           ["changes df in place so that every M becomes Male and returns nothing",
            "builds a dictionary out of the values that are found in the sex column",
            "renames the column called sex so that it is now called M or F"],
           "map() looks each value up in the dictionary. Assign the result back to keep it: df['sex'] = df['sex'].map(...)."),
        mc(c, "Which statement imports pandas under its standard alias?",
           "import pandas as pd", ["import pd as pandas", "from pandas import pd", "import pandas.pd"],
           "The pattern is import <module> as <alias>, and pd is the convention for pandas."),
        mc(c, "Which expression calculates the mean of each column using ONLY the first five rows of df?",
           "df.head().mean()", ["df.mean().head()", "df.mean.head()", "df.head(mean())"],
           "Methods run left to right: head() first picks the rows, then mean() averages them. df.mean().head() would average everything and then keep the first five results."),
        mc(c, "What does df.sort_values('price').head(3) return?",
           "the three rows with the lowest price",
           ["the three rows with the highest price", "the first three rows of df in the original order", "an error, because sort_values returns nothing to chain"],
           "sort_values returns a new sorted DataFrame (ascending by default), so head(3) can be chained onto it."),
        fb(c, "Complete the call that loads an Excel workbook into a DataFrame: budget = pd.______('budget_2024.xlsx')",
           ["read_excel"], "pd.read_excel() reads .xlsx files. It needs an Excel engine such as openpyxl installed."),
        mc(c, "A file called orders.csv sits next to your notebook. Which line reads it into a DataFrame called orders?",
           "orders = pd.read_csv('orders.csv')",
           ["orders.read_csv('orders.csv')", "orders = pd.import_csv('orders.csv')", "orders = read_csv.pd('orders.csv')"],
           "read_csv is a function of the pandas module (pd), and you assign the DataFrame it returns to a name."),
        mc(c, "Which code downloads a CSV from the URL in data_url and saves it as results.csv in the same folder as the notebook?",
           "request.urlretrieve(data_url, filename='results.csv')  (after: from urllib import request)",
           ["request.urlretrieve(data_url, filename='data/results.csv')  (after: from urllib import request)",
            "request.urlopen(data_url, filename='results.csv')  (after: from urllib import request)",
            "request.download(data_url, 'results.csv')  (after: from urllib import request)"],
           "urlretrieve(url, filename=...) saves the file. A path such as data/results.csv would put it in a subfolder instead."),
        mc(c, "A column of prices was imported as text instead of numbers. Which method would reveal this by showing the data type of each column?",
           "df.info()", ["df.count()", "df.nunique()", "df.head(0)"],
           "info() lists every column with its dtype. A price column shown as object instead of float64 usually means text got in."),
        mc(c, "Which method would show you the smallest and largest value in each numeric column at once?",
           "df.describe()", ["df.info()", "df.shape", "df.dtypes"],
           "describe() reports min, max, mean, std and quartiles. info() reports structure: dtypes and non-null counts."),
        mc(c, "What is the difference between a DataFrame's shape and its size?",
           "shape is (rows, columns), while size is the total number of cells",
           ["shape is the total number of cells, while size is (rows, columns)",
            "shape counts only the rows, while size counts only the columns",
            "They are identical, and size is just an older name for shape"],
           "A 250-row, 6-column DataFrame has shape (250, 6) and size 1500."),
        mc(c, "Which statement is true of every pandas Series and every DataFrame?",
           "Each has an index that labels its rows",
           ["Each has columns that are labeled with a name", "Each can hold only numeric values", "Each can hold only a single data type"],
           "A Series has just an index and values; a DataFrame has an index plus labeled columns, and each column can have its own type."),
    ]
    sections = [(n, q) for n, q in SECTIONS]
    sections.insert(5, ("0. Python, Importing and Inspecting Data", imp))

    # ------------------------------------------------------------------ pandas manipulation
    c = "Manipulating & Cleaning Data"
    by["Manipulating and Cleaning Data"].extend([
        mc(c, "Which pair of methods identifies duplicate rows and then removes them?",
           "duplicated() and drop_duplicates()",
           ["find_duplicates() and drop_duplicates()", "duplicated() and remove_duplicates()", "info() and drop_duplicates()"],
           "duplicated() returns True/False for each row; drop_duplicates() returns the DataFrame without the repeats."),
        mc(c, "What is the difference between unique(), nunique() and value_counts() on a column?",
           "unique() lists the distinct values, nunique() counts them, and value_counts() counts how often each one occurs",
           ["unique() counts the distinct values, nunique() lists them, and value_counts() adds them up",
            "unique() counts how often each value occurs, nunique() lists them, and value_counts() sorts them",
            "unique() lists the distinct values, nunique() sorts them, and value_counts() removes duplicates"],
           "For a column with values a, a, b: unique() gives [a, b], nunique() gives 2, value_counts() gives a 2, b 1."),
        mc(c, "Which tasks are typical early steps when cleaning a DataFrame, after you have examined it?",
           "Drop duplicate rows, drop rows and columns you do not need, and rename columns",
           ["Sort the index, convert every column into text, and drop every row that holds a zero",
            "Plot each of the columns, fit a regression model, and then drop all of the outliers",
            "Pivot the data, merge it with another table, and then reset the row index"],
           "Examine first (info, describe, head), then remove what is not needed and tidy the names before dealing with types and missing values."),
        mc(c, "A table has one row per product and one column per region. Which description fits it?",
           "wide format", ["long format", "stacked format", "merged format"],
           "Wide data spreads one variable (region) across several columns. Long data has one row per product-region pair."),
        mc(c, "A survey table has one row per respondent, with separate columns Q1, Q2 and Q3 holding their answers. You need one row for each respondent-and-question pair so that you can plot every answer. What should you do?",
           "Reshape the table from wide to long, for example with melt() or stack()",
           ["Reshape the table from long to wide, for example with pivot() or unstack()",
            "Drop the duplicate rows from the table, using drop_duplicates()",
            "Merge the table with itself, using pd.merge() on the respondent column"],
           "One row per respondent with a column per question is wide format. Plotting and grouping are usually easier on long format."),
        mc(c, "What is binning?",
           "Grouping continuous values into ranges, which can make trends easier to see",
           ["Converting each value into text so that the values can be sorted",
            "Removing the values that fall outside the whiskers of a box plot",
            "Splitting a DataFrame into a training set and a test set"],
           "Binning reduces detail on purpose. A histogram bins automatically, and pd.cut() bins a column explicitly."),
        mc(c, "Which function groups a numeric column into ranges, such as age bands?",
           "pd.cut()", ["pd.bin()", "pd.split()", "pd.band()"],
           "pd.cut(df['age'], bins=[0, 18, 65, 100]) assigns each value to an interval."),
        mc(c, "You change a column in a subset created by filtering df and get a SettingWithCopyWarning. What is the usual fix?",
           "Create the subset with .copy(), or set values on the original with .loc",
           ["Ignore it, since the warning always means that the change was saved to the original",
            "Convert every column of the DataFrame to a string before changing the subset",
            "Delete the original DataFrame first so that only the subset remains"],
           "pandas cannot tell whether your subset is a view or a copy. df2 = df[df['x'] > 1].copy() makes the intent explicit."),
        mc(c, "You have January and February sales tables with identical columns, and you want one table containing every row from both. Which call does that?",
           "pd.concat([jan, feb])",
           ["pd.merge(jan, feb)", "jan.join(feb)", "pd.pivot(jan, feb)"],
           "concat stacks tables one under the other by default. merge and join add columns by matching on a key or the index."),
        mc(c, "By default, pd.merge(df1, df2, on='id') keeps ___.",
           "only the rows whose id appears in both tables (an inner join)",
           ["every row from both tables, with NaN filling the gaps (an outer join)",
            "every row of df1 only, even when no match exists (a left join)",
            "every row of df2 only, even when no match exists (a right join)"],
           "Use how='left', 'right' or 'outer' to change that."),
    ])

    c = "Indexes, Reshaping & Grouping"
    by["Indexes, Reshaping and Grouping"].extend([
        mc(c, "Which code returns only the total units for each product in a DataFrame named orders?",
           "orders.groupby('product')['units'].sum()",
           ["orders.groupby('product').sum('units')", "orders['units'].groupby('product').sum()", "orders.sum('product')['units']"],
           "Group by the category, select the one column to total, then aggregate. Without selecting a column, sum() would add every numeric column."),
        mc(c, "What does df['dept'].value_counts().plot(kind='bar') draw?",
           "a bar for each department, with the height showing how many rows it has",
           ["a histogram that bins the department names into equal-width ranges",
            "a line that follows the number of rows from the first to the last department",
            "a pie slice for each department showing its share of the total salary"],
           "value_counts() gives a count per category, and a bar plot is the right choice for categories."),
        sa(c, "A DataFrame has one row per product and one column per region (North, South), holding sales figures. Explain what stack() and unstack() do, how they differ, and what each would do to this table. State whether the table is wide or long before and after.",
           "The table starts WIDE: each region is its own column.\n\nstack() moves the column labels into the row index. For this table it turns the North and South columns into an inner index level, giving one row per (product, region) pair with a single sales column. The result is LONGER and narrower (long format).\n\nunstack() does the reverse: it moves the inner row-index level back out into columns. Unstacking the stacked result gives back one row per product with a column for each region. The result is WIDER and shorter (wide format).\n\nSo stack = columns to rows (longer); unstack = index level to columns (wider).",
           ["Identifies the starting table as wide (regions spread across columns)",
            "Says stack() moves columns into the row index, making the data longer",
            "Says unstack() moves an index level into columns, making the data wider",
            "Applies both operations to the product/region example correctly"],
           "A common slip is reversing the directions: remember that stack makes the table taller."),
    ])

    SECTIONS[:] = sections
    # renumber so the section names stay in order
    SECTIONS[:] = [("%d. %s" % (i + 1, n.split(". ", 1)[1]), qs) for i, (n, qs) in enumerate(SECTIONS)]
